<?php
/*
This file is part of Glotzenheft.

Glotzenheft is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Glotzenheft is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/**
 * CertificationMovieList200ResponseCertifications
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  App\TmdbApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * tmdb-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.26.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace App\TmdbApi\Model;

use \ArrayAccess;
use \App\TmdbApi\ObjectSerializer;

/**
 * CertificationMovieList200ResponseCertifications Class Doc Comment
 *
 * @category Class
 * @package  App\TmdbApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CertificationMovieList200ResponseCertifications implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'certification_movie_list_200_response_certifications';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'au' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsAUInner[]',
        'bg' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsBGInner[]',
        'br' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsBRInner[]',
        'ca' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsCAInner[]',
        'ca_qc' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsCAQCInner[]',
        'de' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsDEInner[]',
        'dk' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsCAQCInner[]',
        'es' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsESInner[]',
        'fi' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsFIInner[]',
        'fr' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsFRInner[]',
        'gb' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsGBInner[]',
        'hu' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsHUInner[]',
        'in' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsINInner[]',
        'it' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsCAQCInner[]',
        'lt' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsCAQCInner[]',
        'my' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsCAQCInner[]',
        'nl' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsNLInner[]',
        'no' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsNOInner[]',
        'nz' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsNZInner[]',
        'ph' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsCAQCInner[]',
        'pt' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsPTInner[]',
        'ru' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsRUInner[]',
        'se' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsSEInner[]',
        'us' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsUSInner[]',
        'kr' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsKRInner[]',
        'sk' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsSKInner[]',
        'th' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsTHInner[]',
        'mx' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsMXInner[]',
        'id' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsIDInner[]',
        'tr' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsTRInner[]',
        'ar' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsARInner[]',
        'gr' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsGRInner[]',
        'tw' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsTWInner[]',
        'za' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsZAInner[]',
        'sg' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsSGInner[]',
        'ie' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsIEInner[]',
        'pr' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsPRInner[]',
        'jp' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsJPInner[]',
        'vi' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsVIInner[]',
        'ch' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsCHInner[]',
        'il' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsILInner[]',
        'hk' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsHKInner[]',
        'mo' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsMOInner[]',
        'lv' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsLVInner[]',
        'lu' => '\App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsLUInner[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'au' => null,
        'bg' => null,
        'br' => null,
        'ca' => null,
        'ca_qc' => null,
        'de' => null,
        'dk' => null,
        'es' => null,
        'fi' => null,
        'fr' => null,
        'gb' => null,
        'hu' => null,
        'in' => null,
        'it' => null,
        'lt' => null,
        'my' => null,
        'nl' => null,
        'no' => null,
        'nz' => null,
        'ph' => null,
        'pt' => null,
        'ru' => null,
        'se' => null,
        'us' => null,
        'kr' => null,
        'sk' => null,
        'th' => null,
        'mx' => null,
        'id' => null,
        'tr' => null,
        'ar' => null,
        'gr' => null,
        'tw' => null,
        'za' => null,
        'sg' => null,
        'ie' => null,
        'pr' => null,
        'jp' => null,
        'vi' => null,
        'ch' => null,
        'il' => null,
        'hk' => null,
        'mo' => null,
        'lv' => null,
        'lu' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'au' => false,
        'bg' => false,
        'br' => false,
        'ca' => false,
        'ca_qc' => false,
        'de' => false,
        'dk' => false,
        'es' => false,
        'fi' => false,
        'fr' => false,
        'gb' => false,
        'hu' => false,
        'in' => false,
        'it' => false,
        'lt' => false,
        'my' => false,
        'nl' => false,
        'no' => false,
        'nz' => false,
        'ph' => false,
        'pt' => false,
        'ru' => false,
        'se' => false,
        'us' => false,
        'kr' => false,
        'sk' => false,
        'th' => false,
        'mx' => false,
        'id' => false,
        'tr' => false,
        'ar' => false,
        'gr' => false,
        'tw' => false,
        'za' => false,
        'sg' => false,
        'ie' => false,
        'pr' => false,
        'jp' => false,
        'vi' => false,
        'ch' => false,
        'il' => false,
        'hk' => false,
        'mo' => false,
        'lv' => false,
        'lu' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'au' => 'AU',
        'bg' => 'BG',
        'br' => 'BR',
        'ca' => 'CA',
        'ca_qc' => 'CA-QC',
        'de' => 'DE',
        'dk' => 'DK',
        'es' => 'ES',
        'fi' => 'FI',
        'fr' => 'FR',
        'gb' => 'GB',
        'hu' => 'HU',
        'in' => 'IN',
        'it' => 'IT',
        'lt' => 'LT',
        'my' => 'MY',
        'nl' => 'NL',
        'no' => 'NO',
        'nz' => 'NZ',
        'ph' => 'PH',
        'pt' => 'PT',
        'ru' => 'RU',
        'se' => 'SE',
        'us' => 'US',
        'kr' => 'KR',
        'sk' => 'SK',
        'th' => 'TH',
        'mx' => 'MX',
        'id' => 'ID',
        'tr' => 'TR',
        'ar' => 'AR',
        'gr' => 'GR',
        'tw' => 'TW',
        'za' => 'ZA',
        'sg' => 'SG',
        'ie' => 'IE',
        'pr' => 'PR',
        'jp' => 'JP',
        'vi' => 'VI',
        'ch' => 'CH',
        'il' => 'IL',
        'hk' => 'HK',
        'mo' => 'MO',
        'lv' => 'LV',
        'lu' => 'LU'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'au' => 'setAu',
        'bg' => 'setBg',
        'br' => 'setBr',
        'ca' => 'setCa',
        'ca_qc' => 'setCaQc',
        'de' => 'setDe',
        'dk' => 'setDk',
        'es' => 'setEs',
        'fi' => 'setFi',
        'fr' => 'setFr',
        'gb' => 'setGb',
        'hu' => 'setHu',
        'in' => 'setIn',
        'it' => 'setIt',
        'lt' => 'setLt',
        'my' => 'setMy',
        'nl' => 'setNl',
        'no' => 'setNo',
        'nz' => 'setNz',
        'ph' => 'setPh',
        'pt' => 'setPt',
        'ru' => 'setRu',
        'se' => 'setSe',
        'us' => 'setUs',
        'kr' => 'setKr',
        'sk' => 'setSk',
        'th' => 'setTh',
        'mx' => 'setMx',
        'id' => 'setId',
        'tr' => 'setTr',
        'ar' => 'setAr',
        'gr' => 'setGr',
        'tw' => 'setTw',
        'za' => 'setZa',
        'sg' => 'setSg',
        'ie' => 'setIe',
        'pr' => 'setPr',
        'jp' => 'setJp',
        'vi' => 'setVi',
        'ch' => 'setCh',
        'il' => 'setIl',
        'hk' => 'setHk',
        'mo' => 'setMo',
        'lv' => 'setLv',
        'lu' => 'setLu'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'au' => 'getAu',
        'bg' => 'getBg',
        'br' => 'getBr',
        'ca' => 'getCa',
        'ca_qc' => 'getCaQc',
        'de' => 'getDe',
        'dk' => 'getDk',
        'es' => 'getEs',
        'fi' => 'getFi',
        'fr' => 'getFr',
        'gb' => 'getGb',
        'hu' => 'getHu',
        'in' => 'getIn',
        'it' => 'getIt',
        'lt' => 'getLt',
        'my' => 'getMy',
        'nl' => 'getNl',
        'no' => 'getNo',
        'nz' => 'getNz',
        'ph' => 'getPh',
        'pt' => 'getPt',
        'ru' => 'getRu',
        'se' => 'getSe',
        'us' => 'getUs',
        'kr' => 'getKr',
        'sk' => 'getSk',
        'th' => 'getTh',
        'mx' => 'getMx',
        'id' => 'getId',
        'tr' => 'getTr',
        'ar' => 'getAr',
        'gr' => 'getGr',
        'tw' => 'getTw',
        'za' => 'getZa',
        'sg' => 'getSg',
        'ie' => 'getIe',
        'pr' => 'getPr',
        'jp' => 'getJp',
        'vi' => 'getVi',
        'ch' => 'getCh',
        'il' => 'getIl',
        'hk' => 'getHk',
        'mo' => 'getMo',
        'lv' => 'getLv',
        'lu' => 'getLu'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('au', $data ?? [], null);
        $this->setIfExists('bg', $data ?? [], null);
        $this->setIfExists('br', $data ?? [], null);
        $this->setIfExists('ca', $data ?? [], null);
        $this->setIfExists('ca_qc', $data ?? [], null);
        $this->setIfExists('de', $data ?? [], null);
        $this->setIfExists('dk', $data ?? [], null);
        $this->setIfExists('es', $data ?? [], null);
        $this->setIfExists('fi', $data ?? [], null);
        $this->setIfExists('fr', $data ?? [], null);
        $this->setIfExists('gb', $data ?? [], null);
        $this->setIfExists('hu', $data ?? [], null);
        $this->setIfExists('in', $data ?? [], null);
        $this->setIfExists('it', $data ?? [], null);
        $this->setIfExists('lt', $data ?? [], null);
        $this->setIfExists('my', $data ?? [], null);
        $this->setIfExists('nl', $data ?? [], null);
        $this->setIfExists('no', $data ?? [], null);
        $this->setIfExists('nz', $data ?? [], null);
        $this->setIfExists('ph', $data ?? [], null);
        $this->setIfExists('pt', $data ?? [], null);
        $this->setIfExists('ru', $data ?? [], null);
        $this->setIfExists('se', $data ?? [], null);
        $this->setIfExists('us', $data ?? [], null);
        $this->setIfExists('kr', $data ?? [], null);
        $this->setIfExists('sk', $data ?? [], null);
        $this->setIfExists('th', $data ?? [], null);
        $this->setIfExists('mx', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('tr', $data ?? [], null);
        $this->setIfExists('ar', $data ?? [], null);
        $this->setIfExists('gr', $data ?? [], null);
        $this->setIfExists('tw', $data ?? [], null);
        $this->setIfExists('za', $data ?? [], null);
        $this->setIfExists('sg', $data ?? [], null);
        $this->setIfExists('ie', $data ?? [], null);
        $this->setIfExists('pr', $data ?? [], null);
        $this->setIfExists('jp', $data ?? [], null);
        $this->setIfExists('vi', $data ?? [], null);
        $this->setIfExists('ch', $data ?? [], null);
        $this->setIfExists('il', $data ?? [], null);
        $this->setIfExists('hk', $data ?? [], null);
        $this->setIfExists('mo', $data ?? [], null);
        $this->setIfExists('lv', $data ?? [], null);
        $this->setIfExists('lu', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets au
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsAUInner[]|null
     */
    public function getAu()
    {
        return $this->container['au'];
    }

    /**
     * Sets au
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsAUInner[]|null $au au
     *
     * @return self
     */
    public function setAu($au)
    {
        if (is_null($au)) {
            throw new \InvalidArgumentException('non-nullable au cannot be null');
        }
        $this->container['au'] = $au;

        return $this;
    }

    /**
     * Gets bg
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsBGInner[]|null
     */
    public function getBg()
    {
        return $this->container['bg'];
    }

    /**
     * Sets bg
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsBGInner[]|null $bg bg
     *
     * @return self
     */
    public function setBg($bg)
    {
        if (is_null($bg)) {
            throw new \InvalidArgumentException('non-nullable bg cannot be null');
        }
        $this->container['bg'] = $bg;

        return $this;
    }

    /**
     * Gets br
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsBRInner[]|null
     */
    public function getBr()
    {
        return $this->container['br'];
    }

    /**
     * Sets br
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsBRInner[]|null $br br
     *
     * @return self
     */
    public function setBr($br)
    {
        if (is_null($br)) {
            throw new \InvalidArgumentException('non-nullable br cannot be null');
        }
        $this->container['br'] = $br;

        return $this;
    }

    /**
     * Gets ca
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsCAInner[]|null
     */
    public function getCa()
    {
        return $this->container['ca'];
    }

    /**
     * Sets ca
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsCAInner[]|null $ca ca
     *
     * @return self
     */
    public function setCa($ca)
    {
        if (is_null($ca)) {
            throw new \InvalidArgumentException('non-nullable ca cannot be null');
        }
        $this->container['ca'] = $ca;

        return $this;
    }

    /**
     * Gets ca_qc
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsCAQCInner[]|null
     */
    public function getCaQc()
    {
        return $this->container['ca_qc'];
    }

    /**
     * Sets ca_qc
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsCAQCInner[]|null $ca_qc ca_qc
     *
     * @return self
     */
    public function setCaQc($ca_qc)
    {
        if (is_null($ca_qc)) {
            throw new \InvalidArgumentException('non-nullable ca_qc cannot be null');
        }
        $this->container['ca_qc'] = $ca_qc;

        return $this;
    }

    /**
     * Gets de
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsDEInner[]|null
     */
    public function getDe()
    {
        return $this->container['de'];
    }

    /**
     * Sets de
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsDEInner[]|null $de de
     *
     * @return self
     */
    public function setDe($de)
    {
        if (is_null($de)) {
            throw new \InvalidArgumentException('non-nullable de cannot be null');
        }
        $this->container['de'] = $de;

        return $this;
    }

    /**
     * Gets dk
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsCAQCInner[]|null
     */
    public function getDk()
    {
        return $this->container['dk'];
    }

    /**
     * Sets dk
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsCAQCInner[]|null $dk dk
     *
     * @return self
     */
    public function setDk($dk)
    {
        if (is_null($dk)) {
            throw new \InvalidArgumentException('non-nullable dk cannot be null');
        }
        $this->container['dk'] = $dk;

        return $this;
    }

    /**
     * Gets es
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsESInner[]|null
     */
    public function getEs()
    {
        return $this->container['es'];
    }

    /**
     * Sets es
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsESInner[]|null $es es
     *
     * @return self
     */
    public function setEs($es)
    {
        if (is_null($es)) {
            throw new \InvalidArgumentException('non-nullable es cannot be null');
        }
        $this->container['es'] = $es;

        return $this;
    }

    /**
     * Gets fi
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsFIInner[]|null
     */
    public function getFi()
    {
        return $this->container['fi'];
    }

    /**
     * Sets fi
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsFIInner[]|null $fi fi
     *
     * @return self
     */
    public function setFi($fi)
    {
        if (is_null($fi)) {
            throw new \InvalidArgumentException('non-nullable fi cannot be null');
        }
        $this->container['fi'] = $fi;

        return $this;
    }

    /**
     * Gets fr
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsFRInner[]|null
     */
    public function getFr()
    {
        return $this->container['fr'];
    }

    /**
     * Sets fr
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsFRInner[]|null $fr fr
     *
     * @return self
     */
    public function setFr($fr)
    {
        if (is_null($fr)) {
            throw new \InvalidArgumentException('non-nullable fr cannot be null');
        }
        $this->container['fr'] = $fr;

        return $this;
    }

    /**
     * Gets gb
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsGBInner[]|null
     */
    public function getGb()
    {
        return $this->container['gb'];
    }

    /**
     * Sets gb
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsGBInner[]|null $gb gb
     *
     * @return self
     */
    public function setGb($gb)
    {
        if (is_null($gb)) {
            throw new \InvalidArgumentException('non-nullable gb cannot be null');
        }
        $this->container['gb'] = $gb;

        return $this;
    }

    /**
     * Gets hu
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsHUInner[]|null
     */
    public function getHu()
    {
        return $this->container['hu'];
    }

    /**
     * Sets hu
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsHUInner[]|null $hu hu
     *
     * @return self
     */
    public function setHu($hu)
    {
        if (is_null($hu)) {
            throw new \InvalidArgumentException('non-nullable hu cannot be null');
        }
        $this->container['hu'] = $hu;

        return $this;
    }

    /**
     * Gets in
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsINInner[]|null
     */
    public function getIn()
    {
        return $this->container['in'];
    }

    /**
     * Sets in
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsINInner[]|null $in in
     *
     * @return self
     */
    public function setIn($in)
    {
        if (is_null($in)) {
            throw new \InvalidArgumentException('non-nullable in cannot be null');
        }
        $this->container['in'] = $in;

        return $this;
    }

    /**
     * Gets it
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsCAQCInner[]|null
     */
    public function getIt()
    {
        return $this->container['it'];
    }

    /**
     * Sets it
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsCAQCInner[]|null $it it
     *
     * @return self
     */
    public function setIt($it)
    {
        if (is_null($it)) {
            throw new \InvalidArgumentException('non-nullable it cannot be null');
        }
        $this->container['it'] = $it;

        return $this;
    }

    /**
     * Gets lt
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsCAQCInner[]|null
     */
    public function getLt()
    {
        return $this->container['lt'];
    }

    /**
     * Sets lt
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsCAQCInner[]|null $lt lt
     *
     * @return self
     */
    public function setLt($lt)
    {
        if (is_null($lt)) {
            throw new \InvalidArgumentException('non-nullable lt cannot be null');
        }
        $this->container['lt'] = $lt;

        return $this;
    }

    /**
     * Gets my
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsCAQCInner[]|null
     */
    public function getMy()
    {
        return $this->container['my'];
    }

    /**
     * Sets my
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsCAQCInner[]|null $my my
     *
     * @return self
     */
    public function setMy($my)
    {
        if (is_null($my)) {
            throw new \InvalidArgumentException('non-nullable my cannot be null');
        }
        $this->container['my'] = $my;

        return $this;
    }

    /**
     * Gets nl
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsNLInner[]|null
     */
    public function getNl()
    {
        return $this->container['nl'];
    }

    /**
     * Sets nl
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsNLInner[]|null $nl nl
     *
     * @return self
     */
    public function setNl($nl)
    {
        if (is_null($nl)) {
            throw new \InvalidArgumentException('non-nullable nl cannot be null');
        }
        $this->container['nl'] = $nl;

        return $this;
    }

    /**
     * Gets no
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsNOInner[]|null
     */
    public function getNo()
    {
        return $this->container['no'];
    }

    /**
     * Sets no
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsNOInner[]|null $no no
     *
     * @return self
     */
    public function setNo($no)
    {
        if (is_null($no)) {
            throw new \InvalidArgumentException('non-nullable no cannot be null');
        }
        $this->container['no'] = $no;

        return $this;
    }

    /**
     * Gets nz
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsNZInner[]|null
     */
    public function getNz()
    {
        return $this->container['nz'];
    }

    /**
     * Sets nz
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsNZInner[]|null $nz nz
     *
     * @return self
     */
    public function setNz($nz)
    {
        if (is_null($nz)) {
            throw new \InvalidArgumentException('non-nullable nz cannot be null');
        }
        $this->container['nz'] = $nz;

        return $this;
    }

    /**
     * Gets ph
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsCAQCInner[]|null
     */
    public function getPh()
    {
        return $this->container['ph'];
    }

    /**
     * Sets ph
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsCAQCInner[]|null $ph ph
     *
     * @return self
     */
    public function setPh($ph)
    {
        if (is_null($ph)) {
            throw new \InvalidArgumentException('non-nullable ph cannot be null');
        }
        $this->container['ph'] = $ph;

        return $this;
    }

    /**
     * Gets pt
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsPTInner[]|null
     */
    public function getPt()
    {
        return $this->container['pt'];
    }

    /**
     * Sets pt
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsPTInner[]|null $pt pt
     *
     * @return self
     */
    public function setPt($pt)
    {
        if (is_null($pt)) {
            throw new \InvalidArgumentException('non-nullable pt cannot be null');
        }
        $this->container['pt'] = $pt;

        return $this;
    }

    /**
     * Gets ru
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsRUInner[]|null
     */
    public function getRu()
    {
        return $this->container['ru'];
    }

    /**
     * Sets ru
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsRUInner[]|null $ru ru
     *
     * @return self
     */
    public function setRu($ru)
    {
        if (is_null($ru)) {
            throw new \InvalidArgumentException('non-nullable ru cannot be null');
        }
        $this->container['ru'] = $ru;

        return $this;
    }

    /**
     * Gets se
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsSEInner[]|null
     */
    public function getSe()
    {
        return $this->container['se'];
    }

    /**
     * Sets se
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsSEInner[]|null $se se
     *
     * @return self
     */
    public function setSe($se)
    {
        if (is_null($se)) {
            throw new \InvalidArgumentException('non-nullable se cannot be null');
        }
        $this->container['se'] = $se;

        return $this;
    }

    /**
     * Gets us
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsUSInner[]|null
     */
    public function getUs()
    {
        return $this->container['us'];
    }

    /**
     * Sets us
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsUSInner[]|null $us us
     *
     * @return self
     */
    public function setUs($us)
    {
        if (is_null($us)) {
            throw new \InvalidArgumentException('non-nullable us cannot be null');
        }
        $this->container['us'] = $us;

        return $this;
    }

    /**
     * Gets kr
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsKRInner[]|null
     */
    public function getKr()
    {
        return $this->container['kr'];
    }

    /**
     * Sets kr
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsKRInner[]|null $kr kr
     *
     * @return self
     */
    public function setKr($kr)
    {
        if (is_null($kr)) {
            throw new \InvalidArgumentException('non-nullable kr cannot be null');
        }
        $this->container['kr'] = $kr;

        return $this;
    }

    /**
     * Gets sk
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsSKInner[]|null
     */
    public function getSk()
    {
        return $this->container['sk'];
    }

    /**
     * Sets sk
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsSKInner[]|null $sk sk
     *
     * @return self
     */
    public function setSk($sk)
    {
        if (is_null($sk)) {
            throw new \InvalidArgumentException('non-nullable sk cannot be null');
        }
        $this->container['sk'] = $sk;

        return $this;
    }

    /**
     * Gets th
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsTHInner[]|null
     */
    public function getTh()
    {
        return $this->container['th'];
    }

    /**
     * Sets th
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsTHInner[]|null $th th
     *
     * @return self
     */
    public function setTh($th)
    {
        if (is_null($th)) {
            throw new \InvalidArgumentException('non-nullable th cannot be null');
        }
        $this->container['th'] = $th;

        return $this;
    }

    /**
     * Gets mx
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsMXInner[]|null
     */
    public function getMx()
    {
        return $this->container['mx'];
    }

    /**
     * Sets mx
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsMXInner[]|null $mx mx
     *
     * @return self
     */
    public function setMx($mx)
    {
        if (is_null($mx)) {
            throw new \InvalidArgumentException('non-nullable mx cannot be null');
        }
        $this->container['mx'] = $mx;

        return $this;
    }

    /**
     * Gets id
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsIDInner[]|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsIDInner[]|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets tr
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsTRInner[]|null
     */
    public function getTr()
    {
        return $this->container['tr'];
    }

    /**
     * Sets tr
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsTRInner[]|null $tr tr
     *
     * @return self
     */
    public function setTr($tr)
    {
        if (is_null($tr)) {
            throw new \InvalidArgumentException('non-nullable tr cannot be null');
        }
        $this->container['tr'] = $tr;

        return $this;
    }

    /**
     * Gets ar
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsARInner[]|null
     */
    public function getAr()
    {
        return $this->container['ar'];
    }

    /**
     * Sets ar
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsARInner[]|null $ar ar
     *
     * @return self
     */
    public function setAr($ar)
    {
        if (is_null($ar)) {
            throw new \InvalidArgumentException('non-nullable ar cannot be null');
        }
        $this->container['ar'] = $ar;

        return $this;
    }

    /**
     * Gets gr
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsGRInner[]|null
     */
    public function getGr()
    {
        return $this->container['gr'];
    }

    /**
     * Sets gr
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsGRInner[]|null $gr gr
     *
     * @return self
     */
    public function setGr($gr)
    {
        if (is_null($gr)) {
            throw new \InvalidArgumentException('non-nullable gr cannot be null');
        }
        $this->container['gr'] = $gr;

        return $this;
    }

    /**
     * Gets tw
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsTWInner[]|null
     */
    public function getTw()
    {
        return $this->container['tw'];
    }

    /**
     * Sets tw
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsTWInner[]|null $tw tw
     *
     * @return self
     */
    public function setTw($tw)
    {
        if (is_null($tw)) {
            throw new \InvalidArgumentException('non-nullable tw cannot be null');
        }
        $this->container['tw'] = $tw;

        return $this;
    }

    /**
     * Gets za
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsZAInner[]|null
     */
    public function getZa()
    {
        return $this->container['za'];
    }

    /**
     * Sets za
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsZAInner[]|null $za za
     *
     * @return self
     */
    public function setZa($za)
    {
        if (is_null($za)) {
            throw new \InvalidArgumentException('non-nullable za cannot be null');
        }
        $this->container['za'] = $za;

        return $this;
    }

    /**
     * Gets sg
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsSGInner[]|null
     */
    public function getSg()
    {
        return $this->container['sg'];
    }

    /**
     * Sets sg
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsSGInner[]|null $sg sg
     *
     * @return self
     */
    public function setSg($sg)
    {
        if (is_null($sg)) {
            throw new \InvalidArgumentException('non-nullable sg cannot be null');
        }
        $this->container['sg'] = $sg;

        return $this;
    }

    /**
     * Gets ie
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsIEInner[]|null
     */
    public function getIe()
    {
        return $this->container['ie'];
    }

    /**
     * Sets ie
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsIEInner[]|null $ie ie
     *
     * @return self
     */
    public function setIe($ie)
    {
        if (is_null($ie)) {
            throw new \InvalidArgumentException('non-nullable ie cannot be null');
        }
        $this->container['ie'] = $ie;

        return $this;
    }

    /**
     * Gets pr
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsPRInner[]|null
     */
    public function getPr()
    {
        return $this->container['pr'];
    }

    /**
     * Sets pr
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsPRInner[]|null $pr pr
     *
     * @return self
     */
    public function setPr($pr)
    {
        if (is_null($pr)) {
            throw new \InvalidArgumentException('non-nullable pr cannot be null');
        }
        $this->container['pr'] = $pr;

        return $this;
    }

    /**
     * Gets jp
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsJPInner[]|null
     */
    public function getJp()
    {
        return $this->container['jp'];
    }

    /**
     * Sets jp
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsJPInner[]|null $jp jp
     *
     * @return self
     */
    public function setJp($jp)
    {
        if (is_null($jp)) {
            throw new \InvalidArgumentException('non-nullable jp cannot be null');
        }
        $this->container['jp'] = $jp;

        return $this;
    }

    /**
     * Gets vi
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsVIInner[]|null
     */
    public function getVi()
    {
        return $this->container['vi'];
    }

    /**
     * Sets vi
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsVIInner[]|null $vi vi
     *
     * @return self
     */
    public function setVi($vi)
    {
        if (is_null($vi)) {
            throw new \InvalidArgumentException('non-nullable vi cannot be null');
        }
        $this->container['vi'] = $vi;

        return $this;
    }

    /**
     * Gets ch
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsCHInner[]|null
     */
    public function getCh()
    {
        return $this->container['ch'];
    }

    /**
     * Sets ch
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsCHInner[]|null $ch ch
     *
     * @return self
     */
    public function setCh($ch)
    {
        if (is_null($ch)) {
            throw new \InvalidArgumentException('non-nullable ch cannot be null');
        }
        $this->container['ch'] = $ch;

        return $this;
    }

    /**
     * Gets il
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsILInner[]|null
     */
    public function getIl()
    {
        return $this->container['il'];
    }

    /**
     * Sets il
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsILInner[]|null $il il
     *
     * @return self
     */
    public function setIl($il)
    {
        if (is_null($il)) {
            throw new \InvalidArgumentException('non-nullable il cannot be null');
        }
        $this->container['il'] = $il;

        return $this;
    }

    /**
     * Gets hk
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsHKInner[]|null
     */
    public function getHk()
    {
        return $this->container['hk'];
    }

    /**
     * Sets hk
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsHKInner[]|null $hk hk
     *
     * @return self
     */
    public function setHk($hk)
    {
        if (is_null($hk)) {
            throw new \InvalidArgumentException('non-nullable hk cannot be null');
        }
        $this->container['hk'] = $hk;

        return $this;
    }

    /**
     * Gets mo
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsMOInner[]|null
     */
    public function getMo()
    {
        return $this->container['mo'];
    }

    /**
     * Sets mo
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsMOInner[]|null $mo mo
     *
     * @return self
     */
    public function setMo($mo)
    {
        if (is_null($mo)) {
            throw new \InvalidArgumentException('non-nullable mo cannot be null');
        }
        $this->container['mo'] = $mo;

        return $this;
    }

    /**
     * Gets lv
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsLVInner[]|null
     */
    public function getLv()
    {
        return $this->container['lv'];
    }

    /**
     * Sets lv
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsLVInner[]|null $lv lv
     *
     * @return self
     */
    public function setLv($lv)
    {
        if (is_null($lv)) {
            throw new \InvalidArgumentException('non-nullable lv cannot be null');
        }
        $this->container['lv'] = $lv;

        return $this;
    }

    /**
     * Gets lu
     *
     * @return \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsLUInner[]|null
     */
    public function getLu()
    {
        return $this->container['lu'];
    }

    /**
     * Sets lu
     *
     * @param \App\TmdbApi\Model\CertificationMovieList200ResponseCertificationsLUInner[]|null $lu lu
     *
     * @return self
     */
    public function setLu($lu)
    {
        if (is_null($lu)) {
            throw new \InvalidArgumentException('non-nullable lu cannot be null');
        }
        $this->container['lu'] = $lu;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


