<?php
/**
 * MovieWatchProviders200ResponseResults
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  App\TmdbApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * tmdb-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.26.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace App\TmdbApi\Model;

use \ArrayAccess;
use \App\TmdbApi\ObjectSerializer;

/**
 * MovieWatchProviders200ResponseResults Class Doc Comment
 *
 * @category Class
 * @package  App\TmdbApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MovieWatchProviders200ResponseResults implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'movie_watch_providers_200_response_results';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'ae' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsAE',
        'al' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsAL',
        'ar' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsAR',
        'at' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsAT',
        'au' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsAU',
        'ba' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsBA',
        'bb' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsBB',
        'be' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsBE',
        'bg' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsBG',
        'bh' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsBH',
        'bo' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsBO',
        'br' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsBR',
        'bs' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsBS',
        'ca' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsCA',
        'ch' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsCH',
        'cl' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsCL',
        'co' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsCO',
        'cr' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsCR',
        'cv' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsCV',
        'cz' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsCZ',
        'de' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsDE',
        'dk' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsDK',
        'do' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsDO',
        'ec' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsEC',
        'ee' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsEE',
        'eg' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsEG',
        'es' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsES',
        'fi' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsFI',
        'fj' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsFJ',
        'fr' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsFR',
        'gb' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsGB',
        'gf' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsGF',
        'gi' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsGI',
        'gr' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsGR',
        'gt' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsGT',
        'hk' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsHK',
        'hn' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsHN',
        'hr' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsHR',
        'hu' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsHU',
        'id' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsID',
        'ie' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsIE',
        'il' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsIL',
        'in' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsIN',
        'iq' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsIQ',
        'is' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsIS',
        'it' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsIT',
        'jm' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsJM',
        'jo' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsJO',
        'jp' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsJP',
        'kr' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsKR',
        'kw' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsKW',
        'lb' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsLB',
        'li' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsLI',
        'lt' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsLT',
        'lv' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsLV',
        'md' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsMD',
        'mk' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsMK',
        'mt' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsMT',
        'mu' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsMU',
        'mx' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsMX',
        'my' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsMY',
        'mz' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsMZ',
        'nl' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsNL',
        'no' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsNO',
        'nz' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsNZ',
        'om' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsOM',
        'pa' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsPA',
        'pe' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsPE',
        'ph' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsPH',
        'pk' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsPK',
        'pl' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsPL',
        'ps' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsPS',
        'pt' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsPT',
        'py' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsPY',
        'qa' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsQA',
        'ro' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsRO',
        'rs' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsRS',
        'ru' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsRU',
        'sa' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsSA',
        'se' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsSE',
        'sg' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsSG',
        'si' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsSI',
        'sk' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsSK',
        'sm' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsSM',
        'sv' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsSV',
        'th' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsTH',
        'tr' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsTR',
        'tt' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsTT',
        'tw' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsTW',
        'ug' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsUG',
        'us' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsUS',
        'uy' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsUY',
        've' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsVE',
        'ye' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsYE',
        'za' => '\App\TmdbApi\Model\MovieWatchProviders200ResponseResultsZA'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'ae' => null,
        'al' => null,
        'ar' => null,
        'at' => null,
        'au' => null,
        'ba' => null,
        'bb' => null,
        'be' => null,
        'bg' => null,
        'bh' => null,
        'bo' => null,
        'br' => null,
        'bs' => null,
        'ca' => null,
        'ch' => null,
        'cl' => null,
        'co' => null,
        'cr' => null,
        'cv' => null,
        'cz' => null,
        'de' => null,
        'dk' => null,
        'do' => null,
        'ec' => null,
        'ee' => null,
        'eg' => null,
        'es' => null,
        'fi' => null,
        'fj' => null,
        'fr' => null,
        'gb' => null,
        'gf' => null,
        'gi' => null,
        'gr' => null,
        'gt' => null,
        'hk' => null,
        'hn' => null,
        'hr' => null,
        'hu' => null,
        'id' => null,
        'ie' => null,
        'il' => null,
        'in' => null,
        'iq' => null,
        'is' => null,
        'it' => null,
        'jm' => null,
        'jo' => null,
        'jp' => null,
        'kr' => null,
        'kw' => null,
        'lb' => null,
        'li' => null,
        'lt' => null,
        'lv' => null,
        'md' => null,
        'mk' => null,
        'mt' => null,
        'mu' => null,
        'mx' => null,
        'my' => null,
        'mz' => null,
        'nl' => null,
        'no' => null,
        'nz' => null,
        'om' => null,
        'pa' => null,
        'pe' => null,
        'ph' => null,
        'pk' => null,
        'pl' => null,
        'ps' => null,
        'pt' => null,
        'py' => null,
        'qa' => null,
        'ro' => null,
        'rs' => null,
        'ru' => null,
        'sa' => null,
        'se' => null,
        'sg' => null,
        'si' => null,
        'sk' => null,
        'sm' => null,
        'sv' => null,
        'th' => null,
        'tr' => null,
        'tt' => null,
        'tw' => null,
        'ug' => null,
        'us' => null,
        'uy' => null,
        've' => null,
        'ye' => null,
        'za' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'ae' => false,
        'al' => false,
        'ar' => false,
        'at' => false,
        'au' => false,
        'ba' => false,
        'bb' => false,
        'be' => false,
        'bg' => false,
        'bh' => false,
        'bo' => false,
        'br' => false,
        'bs' => false,
        'ca' => false,
        'ch' => false,
        'cl' => false,
        'co' => false,
        'cr' => false,
        'cv' => false,
        'cz' => false,
        'de' => false,
        'dk' => false,
        'do' => false,
        'ec' => false,
        'ee' => false,
        'eg' => false,
        'es' => false,
        'fi' => false,
        'fj' => false,
        'fr' => false,
        'gb' => false,
        'gf' => false,
        'gi' => false,
        'gr' => false,
        'gt' => false,
        'hk' => false,
        'hn' => false,
        'hr' => false,
        'hu' => false,
        'id' => false,
        'ie' => false,
        'il' => false,
        'in' => false,
        'iq' => false,
        'is' => false,
        'it' => false,
        'jm' => false,
        'jo' => false,
        'jp' => false,
        'kr' => false,
        'kw' => false,
        'lb' => false,
        'li' => false,
        'lt' => false,
        'lv' => false,
        'md' => false,
        'mk' => false,
        'mt' => false,
        'mu' => false,
        'mx' => false,
        'my' => false,
        'mz' => false,
        'nl' => false,
        'no' => false,
        'nz' => false,
        'om' => false,
        'pa' => false,
        'pe' => false,
        'ph' => false,
        'pk' => false,
        'pl' => false,
        'ps' => false,
        'pt' => false,
        'py' => false,
        'qa' => false,
        'ro' => false,
        'rs' => false,
        'ru' => false,
        'sa' => false,
        'se' => false,
        'sg' => false,
        'si' => false,
        'sk' => false,
        'sm' => false,
        'sv' => false,
        'th' => false,
        'tr' => false,
        'tt' => false,
        'tw' => false,
        'ug' => false,
        'us' => false,
        'uy' => false,
        've' => false,
        'ye' => false,
        'za' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ae' => 'AE',
        'al' => 'AL',
        'ar' => 'AR',
        'at' => 'AT',
        'au' => 'AU',
        'ba' => 'BA',
        'bb' => 'BB',
        'be' => 'BE',
        'bg' => 'BG',
        'bh' => 'BH',
        'bo' => 'BO',
        'br' => 'BR',
        'bs' => 'BS',
        'ca' => 'CA',
        'ch' => 'CH',
        'cl' => 'CL',
        'co' => 'CO',
        'cr' => 'CR',
        'cv' => 'CV',
        'cz' => 'CZ',
        'de' => 'DE',
        'dk' => 'DK',
        'do' => 'DO',
        'ec' => 'EC',
        'ee' => 'EE',
        'eg' => 'EG',
        'es' => 'ES',
        'fi' => 'FI',
        'fj' => 'FJ',
        'fr' => 'FR',
        'gb' => 'GB',
        'gf' => 'GF',
        'gi' => 'GI',
        'gr' => 'GR',
        'gt' => 'GT',
        'hk' => 'HK',
        'hn' => 'HN',
        'hr' => 'HR',
        'hu' => 'HU',
        'id' => 'ID',
        'ie' => 'IE',
        'il' => 'IL',
        'in' => 'IN',
        'iq' => 'IQ',
        'is' => 'IS',
        'it' => 'IT',
        'jm' => 'JM',
        'jo' => 'JO',
        'jp' => 'JP',
        'kr' => 'KR',
        'kw' => 'KW',
        'lb' => 'LB',
        'li' => 'LI',
        'lt' => 'LT',
        'lv' => 'LV',
        'md' => 'MD',
        'mk' => 'MK',
        'mt' => 'MT',
        'mu' => 'MU',
        'mx' => 'MX',
        'my' => 'MY',
        'mz' => 'MZ',
        'nl' => 'NL',
        'no' => 'NO',
        'nz' => 'NZ',
        'om' => 'OM',
        'pa' => 'PA',
        'pe' => 'PE',
        'ph' => 'PH',
        'pk' => 'PK',
        'pl' => 'PL',
        'ps' => 'PS',
        'pt' => 'PT',
        'py' => 'PY',
        'qa' => 'QA',
        'ro' => 'RO',
        'rs' => 'RS',
        'ru' => 'RU',
        'sa' => 'SA',
        'se' => 'SE',
        'sg' => 'SG',
        'si' => 'SI',
        'sk' => 'SK',
        'sm' => 'SM',
        'sv' => 'SV',
        'th' => 'TH',
        'tr' => 'TR',
        'tt' => 'TT',
        'tw' => 'TW',
        'ug' => 'UG',
        'us' => 'US',
        'uy' => 'UY',
        've' => 'VE',
        'ye' => 'YE',
        'za' => 'ZA'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ae' => 'setAe',
        'al' => 'setAl',
        'ar' => 'setAr',
        'at' => 'setAt',
        'au' => 'setAu',
        'ba' => 'setBa',
        'bb' => 'setBb',
        'be' => 'setBe',
        'bg' => 'setBg',
        'bh' => 'setBh',
        'bo' => 'setBo',
        'br' => 'setBr',
        'bs' => 'setBs',
        'ca' => 'setCa',
        'ch' => 'setCh',
        'cl' => 'setCl',
        'co' => 'setCo',
        'cr' => 'setCr',
        'cv' => 'setCv',
        'cz' => 'setCz',
        'de' => 'setDe',
        'dk' => 'setDk',
        'do' => 'setDo',
        'ec' => 'setEc',
        'ee' => 'setEe',
        'eg' => 'setEg',
        'es' => 'setEs',
        'fi' => 'setFi',
        'fj' => 'setFj',
        'fr' => 'setFr',
        'gb' => 'setGb',
        'gf' => 'setGf',
        'gi' => 'setGi',
        'gr' => 'setGr',
        'gt' => 'setGt',
        'hk' => 'setHk',
        'hn' => 'setHn',
        'hr' => 'setHr',
        'hu' => 'setHu',
        'id' => 'setId',
        'ie' => 'setIe',
        'il' => 'setIl',
        'in' => 'setIn',
        'iq' => 'setIq',
        'is' => 'setIs',
        'it' => 'setIt',
        'jm' => 'setJm',
        'jo' => 'setJo',
        'jp' => 'setJp',
        'kr' => 'setKr',
        'kw' => 'setKw',
        'lb' => 'setLb',
        'li' => 'setLi',
        'lt' => 'setLt',
        'lv' => 'setLv',
        'md' => 'setMd',
        'mk' => 'setMk',
        'mt' => 'setMt',
        'mu' => 'setMu',
        'mx' => 'setMx',
        'my' => 'setMy',
        'mz' => 'setMz',
        'nl' => 'setNl',
        'no' => 'setNo',
        'nz' => 'setNz',
        'om' => 'setOm',
        'pa' => 'setPa',
        'pe' => 'setPe',
        'ph' => 'setPh',
        'pk' => 'setPk',
        'pl' => 'setPl',
        'ps' => 'setPs',
        'pt' => 'setPt',
        'py' => 'setPy',
        'qa' => 'setQa',
        'ro' => 'setRo',
        'rs' => 'setRs',
        'ru' => 'setRu',
        'sa' => 'setSa',
        'se' => 'setSe',
        'sg' => 'setSg',
        'si' => 'setSi',
        'sk' => 'setSk',
        'sm' => 'setSm',
        'sv' => 'setSv',
        'th' => 'setTh',
        'tr' => 'setTr',
        'tt' => 'setTt',
        'tw' => 'setTw',
        'ug' => 'setUg',
        'us' => 'setUs',
        'uy' => 'setUy',
        've' => 'setVe',
        'ye' => 'setYe',
        'za' => 'setZa'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ae' => 'getAe',
        'al' => 'getAl',
        'ar' => 'getAr',
        'at' => 'getAt',
        'au' => 'getAu',
        'ba' => 'getBa',
        'bb' => 'getBb',
        'be' => 'getBe',
        'bg' => 'getBg',
        'bh' => 'getBh',
        'bo' => 'getBo',
        'br' => 'getBr',
        'bs' => 'getBs',
        'ca' => 'getCa',
        'ch' => 'getCh',
        'cl' => 'getCl',
        'co' => 'getCo',
        'cr' => 'getCr',
        'cv' => 'getCv',
        'cz' => 'getCz',
        'de' => 'getDe',
        'dk' => 'getDk',
        'do' => 'getDo',
        'ec' => 'getEc',
        'ee' => 'getEe',
        'eg' => 'getEg',
        'es' => 'getEs',
        'fi' => 'getFi',
        'fj' => 'getFj',
        'fr' => 'getFr',
        'gb' => 'getGb',
        'gf' => 'getGf',
        'gi' => 'getGi',
        'gr' => 'getGr',
        'gt' => 'getGt',
        'hk' => 'getHk',
        'hn' => 'getHn',
        'hr' => 'getHr',
        'hu' => 'getHu',
        'id' => 'getId',
        'ie' => 'getIe',
        'il' => 'getIl',
        'in' => 'getIn',
        'iq' => 'getIq',
        'is' => 'getIs',
        'it' => 'getIt',
        'jm' => 'getJm',
        'jo' => 'getJo',
        'jp' => 'getJp',
        'kr' => 'getKr',
        'kw' => 'getKw',
        'lb' => 'getLb',
        'li' => 'getLi',
        'lt' => 'getLt',
        'lv' => 'getLv',
        'md' => 'getMd',
        'mk' => 'getMk',
        'mt' => 'getMt',
        'mu' => 'getMu',
        'mx' => 'getMx',
        'my' => 'getMy',
        'mz' => 'getMz',
        'nl' => 'getNl',
        'no' => 'getNo',
        'nz' => 'getNz',
        'om' => 'getOm',
        'pa' => 'getPa',
        'pe' => 'getPe',
        'ph' => 'getPh',
        'pk' => 'getPk',
        'pl' => 'getPl',
        'ps' => 'getPs',
        'pt' => 'getPt',
        'py' => 'getPy',
        'qa' => 'getQa',
        'ro' => 'getRo',
        'rs' => 'getRs',
        'ru' => 'getRu',
        'sa' => 'getSa',
        'se' => 'getSe',
        'sg' => 'getSg',
        'si' => 'getSi',
        'sk' => 'getSk',
        'sm' => 'getSm',
        'sv' => 'getSv',
        'th' => 'getTh',
        'tr' => 'getTr',
        'tt' => 'getTt',
        'tw' => 'getTw',
        'ug' => 'getUg',
        'us' => 'getUs',
        'uy' => 'getUy',
        've' => 'getVe',
        'ye' => 'getYe',
        'za' => 'getZa'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('ae', $data ?? [], null);
        $this->setIfExists('al', $data ?? [], null);
        $this->setIfExists('ar', $data ?? [], null);
        $this->setIfExists('at', $data ?? [], null);
        $this->setIfExists('au', $data ?? [], null);
        $this->setIfExists('ba', $data ?? [], null);
        $this->setIfExists('bb', $data ?? [], null);
        $this->setIfExists('be', $data ?? [], null);
        $this->setIfExists('bg', $data ?? [], null);
        $this->setIfExists('bh', $data ?? [], null);
        $this->setIfExists('bo', $data ?? [], null);
        $this->setIfExists('br', $data ?? [], null);
        $this->setIfExists('bs', $data ?? [], null);
        $this->setIfExists('ca', $data ?? [], null);
        $this->setIfExists('ch', $data ?? [], null);
        $this->setIfExists('cl', $data ?? [], null);
        $this->setIfExists('co', $data ?? [], null);
        $this->setIfExists('cr', $data ?? [], null);
        $this->setIfExists('cv', $data ?? [], null);
        $this->setIfExists('cz', $data ?? [], null);
        $this->setIfExists('de', $data ?? [], null);
        $this->setIfExists('dk', $data ?? [], null);
        $this->setIfExists('do', $data ?? [], null);
        $this->setIfExists('ec', $data ?? [], null);
        $this->setIfExists('ee', $data ?? [], null);
        $this->setIfExists('eg', $data ?? [], null);
        $this->setIfExists('es', $data ?? [], null);
        $this->setIfExists('fi', $data ?? [], null);
        $this->setIfExists('fj', $data ?? [], null);
        $this->setIfExists('fr', $data ?? [], null);
        $this->setIfExists('gb', $data ?? [], null);
        $this->setIfExists('gf', $data ?? [], null);
        $this->setIfExists('gi', $data ?? [], null);
        $this->setIfExists('gr', $data ?? [], null);
        $this->setIfExists('gt', $data ?? [], null);
        $this->setIfExists('hk', $data ?? [], null);
        $this->setIfExists('hn', $data ?? [], null);
        $this->setIfExists('hr', $data ?? [], null);
        $this->setIfExists('hu', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('ie', $data ?? [], null);
        $this->setIfExists('il', $data ?? [], null);
        $this->setIfExists('in', $data ?? [], null);
        $this->setIfExists('iq', $data ?? [], null);
        $this->setIfExists('is', $data ?? [], null);
        $this->setIfExists('it', $data ?? [], null);
        $this->setIfExists('jm', $data ?? [], null);
        $this->setIfExists('jo', $data ?? [], null);
        $this->setIfExists('jp', $data ?? [], null);
        $this->setIfExists('kr', $data ?? [], null);
        $this->setIfExists('kw', $data ?? [], null);
        $this->setIfExists('lb', $data ?? [], null);
        $this->setIfExists('li', $data ?? [], null);
        $this->setIfExists('lt', $data ?? [], null);
        $this->setIfExists('lv', $data ?? [], null);
        $this->setIfExists('md', $data ?? [], null);
        $this->setIfExists('mk', $data ?? [], null);
        $this->setIfExists('mt', $data ?? [], null);
        $this->setIfExists('mu', $data ?? [], null);
        $this->setIfExists('mx', $data ?? [], null);
        $this->setIfExists('my', $data ?? [], null);
        $this->setIfExists('mz', $data ?? [], null);
        $this->setIfExists('nl', $data ?? [], null);
        $this->setIfExists('no', $data ?? [], null);
        $this->setIfExists('nz', $data ?? [], null);
        $this->setIfExists('om', $data ?? [], null);
        $this->setIfExists('pa', $data ?? [], null);
        $this->setIfExists('pe', $data ?? [], null);
        $this->setIfExists('ph', $data ?? [], null);
        $this->setIfExists('pk', $data ?? [], null);
        $this->setIfExists('pl', $data ?? [], null);
        $this->setIfExists('ps', $data ?? [], null);
        $this->setIfExists('pt', $data ?? [], null);
        $this->setIfExists('py', $data ?? [], null);
        $this->setIfExists('qa', $data ?? [], null);
        $this->setIfExists('ro', $data ?? [], null);
        $this->setIfExists('rs', $data ?? [], null);
        $this->setIfExists('ru', $data ?? [], null);
        $this->setIfExists('sa', $data ?? [], null);
        $this->setIfExists('se', $data ?? [], null);
        $this->setIfExists('sg', $data ?? [], null);
        $this->setIfExists('si', $data ?? [], null);
        $this->setIfExists('sk', $data ?? [], null);
        $this->setIfExists('sm', $data ?? [], null);
        $this->setIfExists('sv', $data ?? [], null);
        $this->setIfExists('th', $data ?? [], null);
        $this->setIfExists('tr', $data ?? [], null);
        $this->setIfExists('tt', $data ?? [], null);
        $this->setIfExists('tw', $data ?? [], null);
        $this->setIfExists('ug', $data ?? [], null);
        $this->setIfExists('us', $data ?? [], null);
        $this->setIfExists('uy', $data ?? [], null);
        $this->setIfExists('ve', $data ?? [], null);
        $this->setIfExists('ye', $data ?? [], null);
        $this->setIfExists('za', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ae
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsAE|null
     */
    public function getAe()
    {
        return $this->container['ae'];
    }

    /**
     * Sets ae
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsAE|null $ae ae
     *
     * @return self
     */
    public function setAe($ae)
    {
        if (is_null($ae)) {
            throw new \InvalidArgumentException('non-nullable ae cannot be null');
        }
        $this->container['ae'] = $ae;

        return $this;
    }

    /**
     * Gets al
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsAL|null
     */
    public function getAl()
    {
        return $this->container['al'];
    }

    /**
     * Sets al
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsAL|null $al al
     *
     * @return self
     */
    public function setAl($al)
    {
        if (is_null($al)) {
            throw new \InvalidArgumentException('non-nullable al cannot be null');
        }
        $this->container['al'] = $al;

        return $this;
    }

    /**
     * Gets ar
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsAR|null
     */
    public function getAr()
    {
        return $this->container['ar'];
    }

    /**
     * Sets ar
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsAR|null $ar ar
     *
     * @return self
     */
    public function setAr($ar)
    {
        if (is_null($ar)) {
            throw new \InvalidArgumentException('non-nullable ar cannot be null');
        }
        $this->container['ar'] = $ar;

        return $this;
    }

    /**
     * Gets at
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsAT|null
     */
    public function getAt()
    {
        return $this->container['at'];
    }

    /**
     * Sets at
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsAT|null $at at
     *
     * @return self
     */
    public function setAt($at)
    {
        if (is_null($at)) {
            throw new \InvalidArgumentException('non-nullable at cannot be null');
        }
        $this->container['at'] = $at;

        return $this;
    }

    /**
     * Gets au
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsAU|null
     */
    public function getAu()
    {
        return $this->container['au'];
    }

    /**
     * Sets au
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsAU|null $au au
     *
     * @return self
     */
    public function setAu($au)
    {
        if (is_null($au)) {
            throw new \InvalidArgumentException('non-nullable au cannot be null');
        }
        $this->container['au'] = $au;

        return $this;
    }

    /**
     * Gets ba
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsBA|null
     */
    public function getBa()
    {
        return $this->container['ba'];
    }

    /**
     * Sets ba
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsBA|null $ba ba
     *
     * @return self
     */
    public function setBa($ba)
    {
        if (is_null($ba)) {
            throw new \InvalidArgumentException('non-nullable ba cannot be null');
        }
        $this->container['ba'] = $ba;

        return $this;
    }

    /**
     * Gets bb
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsBB|null
     */
    public function getBb()
    {
        return $this->container['bb'];
    }

    /**
     * Sets bb
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsBB|null $bb bb
     *
     * @return self
     */
    public function setBb($bb)
    {
        if (is_null($bb)) {
            throw new \InvalidArgumentException('non-nullable bb cannot be null');
        }
        $this->container['bb'] = $bb;

        return $this;
    }

    /**
     * Gets be
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsBE|null
     */
    public function getBe()
    {
        return $this->container['be'];
    }

    /**
     * Sets be
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsBE|null $be be
     *
     * @return self
     */
    public function setBe($be)
    {
        if (is_null($be)) {
            throw new \InvalidArgumentException('non-nullable be cannot be null');
        }
        $this->container['be'] = $be;

        return $this;
    }

    /**
     * Gets bg
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsBG|null
     */
    public function getBg()
    {
        return $this->container['bg'];
    }

    /**
     * Sets bg
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsBG|null $bg bg
     *
     * @return self
     */
    public function setBg($bg)
    {
        if (is_null($bg)) {
            throw new \InvalidArgumentException('non-nullable bg cannot be null');
        }
        $this->container['bg'] = $bg;

        return $this;
    }

    /**
     * Gets bh
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsBH|null
     */
    public function getBh()
    {
        return $this->container['bh'];
    }

    /**
     * Sets bh
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsBH|null $bh bh
     *
     * @return self
     */
    public function setBh($bh)
    {
        if (is_null($bh)) {
            throw new \InvalidArgumentException('non-nullable bh cannot be null');
        }
        $this->container['bh'] = $bh;

        return $this;
    }

    /**
     * Gets bo
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsBO|null
     */
    public function getBo()
    {
        return $this->container['bo'];
    }

    /**
     * Sets bo
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsBO|null $bo bo
     *
     * @return self
     */
    public function setBo($bo)
    {
        if (is_null($bo)) {
            throw new \InvalidArgumentException('non-nullable bo cannot be null');
        }
        $this->container['bo'] = $bo;

        return $this;
    }

    /**
     * Gets br
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsBR|null
     */
    public function getBr()
    {
        return $this->container['br'];
    }

    /**
     * Sets br
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsBR|null $br br
     *
     * @return self
     */
    public function setBr($br)
    {
        if (is_null($br)) {
            throw new \InvalidArgumentException('non-nullable br cannot be null');
        }
        $this->container['br'] = $br;

        return $this;
    }

    /**
     * Gets bs
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsBS|null
     */
    public function getBs()
    {
        return $this->container['bs'];
    }

    /**
     * Sets bs
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsBS|null $bs bs
     *
     * @return self
     */
    public function setBs($bs)
    {
        if (is_null($bs)) {
            throw new \InvalidArgumentException('non-nullable bs cannot be null');
        }
        $this->container['bs'] = $bs;

        return $this;
    }

    /**
     * Gets ca
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsCA|null
     */
    public function getCa()
    {
        return $this->container['ca'];
    }

    /**
     * Sets ca
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsCA|null $ca ca
     *
     * @return self
     */
    public function setCa($ca)
    {
        if (is_null($ca)) {
            throw new \InvalidArgumentException('non-nullable ca cannot be null');
        }
        $this->container['ca'] = $ca;

        return $this;
    }

    /**
     * Gets ch
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsCH|null
     */
    public function getCh()
    {
        return $this->container['ch'];
    }

    /**
     * Sets ch
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsCH|null $ch ch
     *
     * @return self
     */
    public function setCh($ch)
    {
        if (is_null($ch)) {
            throw new \InvalidArgumentException('non-nullable ch cannot be null');
        }
        $this->container['ch'] = $ch;

        return $this;
    }

    /**
     * Gets cl
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsCL|null
     */
    public function getCl()
    {
        return $this->container['cl'];
    }

    /**
     * Sets cl
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsCL|null $cl cl
     *
     * @return self
     */
    public function setCl($cl)
    {
        if (is_null($cl)) {
            throw new \InvalidArgumentException('non-nullable cl cannot be null');
        }
        $this->container['cl'] = $cl;

        return $this;
    }

    /**
     * Gets co
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsCO|null
     */
    public function getCo()
    {
        return $this->container['co'];
    }

    /**
     * Sets co
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsCO|null $co co
     *
     * @return self
     */
    public function setCo($co)
    {
        if (is_null($co)) {
            throw new \InvalidArgumentException('non-nullable co cannot be null');
        }
        $this->container['co'] = $co;

        return $this;
    }

    /**
     * Gets cr
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsCR|null
     */
    public function getCr()
    {
        return $this->container['cr'];
    }

    /**
     * Sets cr
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsCR|null $cr cr
     *
     * @return self
     */
    public function setCr($cr)
    {
        if (is_null($cr)) {
            throw new \InvalidArgumentException('non-nullable cr cannot be null');
        }
        $this->container['cr'] = $cr;

        return $this;
    }

    /**
     * Gets cv
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsCV|null
     */
    public function getCv()
    {
        return $this->container['cv'];
    }

    /**
     * Sets cv
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsCV|null $cv cv
     *
     * @return self
     */
    public function setCv($cv)
    {
        if (is_null($cv)) {
            throw new \InvalidArgumentException('non-nullable cv cannot be null');
        }
        $this->container['cv'] = $cv;

        return $this;
    }

    /**
     * Gets cz
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsCZ|null
     */
    public function getCz()
    {
        return $this->container['cz'];
    }

    /**
     * Sets cz
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsCZ|null $cz cz
     *
     * @return self
     */
    public function setCz($cz)
    {
        if (is_null($cz)) {
            throw new \InvalidArgumentException('non-nullable cz cannot be null');
        }
        $this->container['cz'] = $cz;

        return $this;
    }

    /**
     * Gets de
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsDE|null
     */
    public function getDe()
    {
        return $this->container['de'];
    }

    /**
     * Sets de
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsDE|null $de de
     *
     * @return self
     */
    public function setDe($de)
    {
        if (is_null($de)) {
            throw new \InvalidArgumentException('non-nullable de cannot be null');
        }
        $this->container['de'] = $de;

        return $this;
    }

    /**
     * Gets dk
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsDK|null
     */
    public function getDk()
    {
        return $this->container['dk'];
    }

    /**
     * Sets dk
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsDK|null $dk dk
     *
     * @return self
     */
    public function setDk($dk)
    {
        if (is_null($dk)) {
            throw new \InvalidArgumentException('non-nullable dk cannot be null');
        }
        $this->container['dk'] = $dk;

        return $this;
    }

    /**
     * Gets do
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsDO|null
     */
    public function getDo()
    {
        return $this->container['do'];
    }

    /**
     * Sets do
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsDO|null $do do
     *
     * @return self
     */
    public function setDo($do)
    {
        if (is_null($do)) {
            throw new \InvalidArgumentException('non-nullable do cannot be null');
        }
        $this->container['do'] = $do;

        return $this;
    }

    /**
     * Gets ec
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsEC|null
     */
    public function getEc()
    {
        return $this->container['ec'];
    }

    /**
     * Sets ec
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsEC|null $ec ec
     *
     * @return self
     */
    public function setEc($ec)
    {
        if (is_null($ec)) {
            throw new \InvalidArgumentException('non-nullable ec cannot be null');
        }
        $this->container['ec'] = $ec;

        return $this;
    }

    /**
     * Gets ee
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsEE|null
     */
    public function getEe()
    {
        return $this->container['ee'];
    }

    /**
     * Sets ee
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsEE|null $ee ee
     *
     * @return self
     */
    public function setEe($ee)
    {
        if (is_null($ee)) {
            throw new \InvalidArgumentException('non-nullable ee cannot be null');
        }
        $this->container['ee'] = $ee;

        return $this;
    }

    /**
     * Gets eg
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsEG|null
     */
    public function getEg()
    {
        return $this->container['eg'];
    }

    /**
     * Sets eg
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsEG|null $eg eg
     *
     * @return self
     */
    public function setEg($eg)
    {
        if (is_null($eg)) {
            throw new \InvalidArgumentException('non-nullable eg cannot be null');
        }
        $this->container['eg'] = $eg;

        return $this;
    }

    /**
     * Gets es
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsES|null
     */
    public function getEs()
    {
        return $this->container['es'];
    }

    /**
     * Sets es
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsES|null $es es
     *
     * @return self
     */
    public function setEs($es)
    {
        if (is_null($es)) {
            throw new \InvalidArgumentException('non-nullable es cannot be null');
        }
        $this->container['es'] = $es;

        return $this;
    }

    /**
     * Gets fi
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsFI|null
     */
    public function getFi()
    {
        return $this->container['fi'];
    }

    /**
     * Sets fi
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsFI|null $fi fi
     *
     * @return self
     */
    public function setFi($fi)
    {
        if (is_null($fi)) {
            throw new \InvalidArgumentException('non-nullable fi cannot be null');
        }
        $this->container['fi'] = $fi;

        return $this;
    }

    /**
     * Gets fj
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsFJ|null
     */
    public function getFj()
    {
        return $this->container['fj'];
    }

    /**
     * Sets fj
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsFJ|null $fj fj
     *
     * @return self
     */
    public function setFj($fj)
    {
        if (is_null($fj)) {
            throw new \InvalidArgumentException('non-nullable fj cannot be null');
        }
        $this->container['fj'] = $fj;

        return $this;
    }

    /**
     * Gets fr
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsFR|null
     */
    public function getFr()
    {
        return $this->container['fr'];
    }

    /**
     * Sets fr
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsFR|null $fr fr
     *
     * @return self
     */
    public function setFr($fr)
    {
        if (is_null($fr)) {
            throw new \InvalidArgumentException('non-nullable fr cannot be null');
        }
        $this->container['fr'] = $fr;

        return $this;
    }

    /**
     * Gets gb
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsGB|null
     */
    public function getGb()
    {
        return $this->container['gb'];
    }

    /**
     * Sets gb
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsGB|null $gb gb
     *
     * @return self
     */
    public function setGb($gb)
    {
        if (is_null($gb)) {
            throw new \InvalidArgumentException('non-nullable gb cannot be null');
        }
        $this->container['gb'] = $gb;

        return $this;
    }

    /**
     * Gets gf
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsGF|null
     */
    public function getGf()
    {
        return $this->container['gf'];
    }

    /**
     * Sets gf
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsGF|null $gf gf
     *
     * @return self
     */
    public function setGf($gf)
    {
        if (is_null($gf)) {
            throw new \InvalidArgumentException('non-nullable gf cannot be null');
        }
        $this->container['gf'] = $gf;

        return $this;
    }

    /**
     * Gets gi
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsGI|null
     */
    public function getGi()
    {
        return $this->container['gi'];
    }

    /**
     * Sets gi
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsGI|null $gi gi
     *
     * @return self
     */
    public function setGi($gi)
    {
        if (is_null($gi)) {
            throw new \InvalidArgumentException('non-nullable gi cannot be null');
        }
        $this->container['gi'] = $gi;

        return $this;
    }

    /**
     * Gets gr
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsGR|null
     */
    public function getGr()
    {
        return $this->container['gr'];
    }

    /**
     * Sets gr
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsGR|null $gr gr
     *
     * @return self
     */
    public function setGr($gr)
    {
        if (is_null($gr)) {
            throw new \InvalidArgumentException('non-nullable gr cannot be null');
        }
        $this->container['gr'] = $gr;

        return $this;
    }

    /**
     * Gets gt
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsGT|null
     */
    public function getGt()
    {
        return $this->container['gt'];
    }

    /**
     * Sets gt
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsGT|null $gt gt
     *
     * @return self
     */
    public function setGt($gt)
    {
        if (is_null($gt)) {
            throw new \InvalidArgumentException('non-nullable gt cannot be null');
        }
        $this->container['gt'] = $gt;

        return $this;
    }

    /**
     * Gets hk
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsHK|null
     */
    public function getHk()
    {
        return $this->container['hk'];
    }

    /**
     * Sets hk
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsHK|null $hk hk
     *
     * @return self
     */
    public function setHk($hk)
    {
        if (is_null($hk)) {
            throw new \InvalidArgumentException('non-nullable hk cannot be null');
        }
        $this->container['hk'] = $hk;

        return $this;
    }

    /**
     * Gets hn
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsHN|null
     */
    public function getHn()
    {
        return $this->container['hn'];
    }

    /**
     * Sets hn
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsHN|null $hn hn
     *
     * @return self
     */
    public function setHn($hn)
    {
        if (is_null($hn)) {
            throw new \InvalidArgumentException('non-nullable hn cannot be null');
        }
        $this->container['hn'] = $hn;

        return $this;
    }

    /**
     * Gets hr
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsHR|null
     */
    public function getHr()
    {
        return $this->container['hr'];
    }

    /**
     * Sets hr
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsHR|null $hr hr
     *
     * @return self
     */
    public function setHr($hr)
    {
        if (is_null($hr)) {
            throw new \InvalidArgumentException('non-nullable hr cannot be null');
        }
        $this->container['hr'] = $hr;

        return $this;
    }

    /**
     * Gets hu
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsHU|null
     */
    public function getHu()
    {
        return $this->container['hu'];
    }

    /**
     * Sets hu
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsHU|null $hu hu
     *
     * @return self
     */
    public function setHu($hu)
    {
        if (is_null($hu)) {
            throw new \InvalidArgumentException('non-nullable hu cannot be null');
        }
        $this->container['hu'] = $hu;

        return $this;
    }

    /**
     * Gets id
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsID|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsID|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets ie
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsIE|null
     */
    public function getIe()
    {
        return $this->container['ie'];
    }

    /**
     * Sets ie
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsIE|null $ie ie
     *
     * @return self
     */
    public function setIe($ie)
    {
        if (is_null($ie)) {
            throw new \InvalidArgumentException('non-nullable ie cannot be null');
        }
        $this->container['ie'] = $ie;

        return $this;
    }

    /**
     * Gets il
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsIL|null
     */
    public function getIl()
    {
        return $this->container['il'];
    }

    /**
     * Sets il
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsIL|null $il il
     *
     * @return self
     */
    public function setIl($il)
    {
        if (is_null($il)) {
            throw new \InvalidArgumentException('non-nullable il cannot be null');
        }
        $this->container['il'] = $il;

        return $this;
    }

    /**
     * Gets in
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsIN|null
     */
    public function getIn()
    {
        return $this->container['in'];
    }

    /**
     * Sets in
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsIN|null $in in
     *
     * @return self
     */
    public function setIn($in)
    {
        if (is_null($in)) {
            throw new \InvalidArgumentException('non-nullable in cannot be null');
        }
        $this->container['in'] = $in;

        return $this;
    }

    /**
     * Gets iq
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsIQ|null
     */
    public function getIq()
    {
        return $this->container['iq'];
    }

    /**
     * Sets iq
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsIQ|null $iq iq
     *
     * @return self
     */
    public function setIq($iq)
    {
        if (is_null($iq)) {
            throw new \InvalidArgumentException('non-nullable iq cannot be null');
        }
        $this->container['iq'] = $iq;

        return $this;
    }

    /**
     * Gets is
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsIS|null
     */
    public function getIs()
    {
        return $this->container['is'];
    }

    /**
     * Sets is
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsIS|null $is is
     *
     * @return self
     */
    public function setIs($is)
    {
        if (is_null($is)) {
            throw new \InvalidArgumentException('non-nullable is cannot be null');
        }
        $this->container['is'] = $is;

        return $this;
    }

    /**
     * Gets it
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsIT|null
     */
    public function getIt()
    {
        return $this->container['it'];
    }

    /**
     * Sets it
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsIT|null $it it
     *
     * @return self
     */
    public function setIt($it)
    {
        if (is_null($it)) {
            throw new \InvalidArgumentException('non-nullable it cannot be null');
        }
        $this->container['it'] = $it;

        return $this;
    }

    /**
     * Gets jm
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsJM|null
     */
    public function getJm()
    {
        return $this->container['jm'];
    }

    /**
     * Sets jm
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsJM|null $jm jm
     *
     * @return self
     */
    public function setJm($jm)
    {
        if (is_null($jm)) {
            throw new \InvalidArgumentException('non-nullable jm cannot be null');
        }
        $this->container['jm'] = $jm;

        return $this;
    }

    /**
     * Gets jo
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsJO|null
     */
    public function getJo()
    {
        return $this->container['jo'];
    }

    /**
     * Sets jo
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsJO|null $jo jo
     *
     * @return self
     */
    public function setJo($jo)
    {
        if (is_null($jo)) {
            throw new \InvalidArgumentException('non-nullable jo cannot be null');
        }
        $this->container['jo'] = $jo;

        return $this;
    }

    /**
     * Gets jp
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsJP|null
     */
    public function getJp()
    {
        return $this->container['jp'];
    }

    /**
     * Sets jp
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsJP|null $jp jp
     *
     * @return self
     */
    public function setJp($jp)
    {
        if (is_null($jp)) {
            throw new \InvalidArgumentException('non-nullable jp cannot be null');
        }
        $this->container['jp'] = $jp;

        return $this;
    }

    /**
     * Gets kr
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsKR|null
     */
    public function getKr()
    {
        return $this->container['kr'];
    }

    /**
     * Sets kr
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsKR|null $kr kr
     *
     * @return self
     */
    public function setKr($kr)
    {
        if (is_null($kr)) {
            throw new \InvalidArgumentException('non-nullable kr cannot be null');
        }
        $this->container['kr'] = $kr;

        return $this;
    }

    /**
     * Gets kw
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsKW|null
     */
    public function getKw()
    {
        return $this->container['kw'];
    }

    /**
     * Sets kw
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsKW|null $kw kw
     *
     * @return self
     */
    public function setKw($kw)
    {
        if (is_null($kw)) {
            throw new \InvalidArgumentException('non-nullable kw cannot be null');
        }
        $this->container['kw'] = $kw;

        return $this;
    }

    /**
     * Gets lb
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsLB|null
     */
    public function getLb()
    {
        return $this->container['lb'];
    }

    /**
     * Sets lb
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsLB|null $lb lb
     *
     * @return self
     */
    public function setLb($lb)
    {
        if (is_null($lb)) {
            throw new \InvalidArgumentException('non-nullable lb cannot be null');
        }
        $this->container['lb'] = $lb;

        return $this;
    }

    /**
     * Gets li
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsLI|null
     */
    public function getLi()
    {
        return $this->container['li'];
    }

    /**
     * Sets li
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsLI|null $li li
     *
     * @return self
     */
    public function setLi($li)
    {
        if (is_null($li)) {
            throw new \InvalidArgumentException('non-nullable li cannot be null');
        }
        $this->container['li'] = $li;

        return $this;
    }

    /**
     * Gets lt
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsLT|null
     */
    public function getLt()
    {
        return $this->container['lt'];
    }

    /**
     * Sets lt
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsLT|null $lt lt
     *
     * @return self
     */
    public function setLt($lt)
    {
        if (is_null($lt)) {
            throw new \InvalidArgumentException('non-nullable lt cannot be null');
        }
        $this->container['lt'] = $lt;

        return $this;
    }

    /**
     * Gets lv
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsLV|null
     */
    public function getLv()
    {
        return $this->container['lv'];
    }

    /**
     * Sets lv
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsLV|null $lv lv
     *
     * @return self
     */
    public function setLv($lv)
    {
        if (is_null($lv)) {
            throw new \InvalidArgumentException('non-nullable lv cannot be null');
        }
        $this->container['lv'] = $lv;

        return $this;
    }

    /**
     * Gets md
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsMD|null
     */
    public function getMd()
    {
        return $this->container['md'];
    }

    /**
     * Sets md
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsMD|null $md md
     *
     * @return self
     */
    public function setMd($md)
    {
        if (is_null($md)) {
            throw new \InvalidArgumentException('non-nullable md cannot be null');
        }
        $this->container['md'] = $md;

        return $this;
    }

    /**
     * Gets mk
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsMK|null
     */
    public function getMk()
    {
        return $this->container['mk'];
    }

    /**
     * Sets mk
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsMK|null $mk mk
     *
     * @return self
     */
    public function setMk($mk)
    {
        if (is_null($mk)) {
            throw new \InvalidArgumentException('non-nullable mk cannot be null');
        }
        $this->container['mk'] = $mk;

        return $this;
    }

    /**
     * Gets mt
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsMT|null
     */
    public function getMt()
    {
        return $this->container['mt'];
    }

    /**
     * Sets mt
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsMT|null $mt mt
     *
     * @return self
     */
    public function setMt($mt)
    {
        if (is_null($mt)) {
            throw new \InvalidArgumentException('non-nullable mt cannot be null');
        }
        $this->container['mt'] = $mt;

        return $this;
    }

    /**
     * Gets mu
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsMU|null
     */
    public function getMu()
    {
        return $this->container['mu'];
    }

    /**
     * Sets mu
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsMU|null $mu mu
     *
     * @return self
     */
    public function setMu($mu)
    {
        if (is_null($mu)) {
            throw new \InvalidArgumentException('non-nullable mu cannot be null');
        }
        $this->container['mu'] = $mu;

        return $this;
    }

    /**
     * Gets mx
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsMX|null
     */
    public function getMx()
    {
        return $this->container['mx'];
    }

    /**
     * Sets mx
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsMX|null $mx mx
     *
     * @return self
     */
    public function setMx($mx)
    {
        if (is_null($mx)) {
            throw new \InvalidArgumentException('non-nullable mx cannot be null');
        }
        $this->container['mx'] = $mx;

        return $this;
    }

    /**
     * Gets my
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsMY|null
     */
    public function getMy()
    {
        return $this->container['my'];
    }

    /**
     * Sets my
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsMY|null $my my
     *
     * @return self
     */
    public function setMy($my)
    {
        if (is_null($my)) {
            throw new \InvalidArgumentException('non-nullable my cannot be null');
        }
        $this->container['my'] = $my;

        return $this;
    }

    /**
     * Gets mz
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsMZ|null
     */
    public function getMz()
    {
        return $this->container['mz'];
    }

    /**
     * Sets mz
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsMZ|null $mz mz
     *
     * @return self
     */
    public function setMz($mz)
    {
        if (is_null($mz)) {
            throw new \InvalidArgumentException('non-nullable mz cannot be null');
        }
        $this->container['mz'] = $mz;

        return $this;
    }

    /**
     * Gets nl
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsNL|null
     */
    public function getNl()
    {
        return $this->container['nl'];
    }

    /**
     * Sets nl
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsNL|null $nl nl
     *
     * @return self
     */
    public function setNl($nl)
    {
        if (is_null($nl)) {
            throw new \InvalidArgumentException('non-nullable nl cannot be null');
        }
        $this->container['nl'] = $nl;

        return $this;
    }

    /**
     * Gets no
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsNO|null
     */
    public function getNo()
    {
        return $this->container['no'];
    }

    /**
     * Sets no
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsNO|null $no no
     *
     * @return self
     */
    public function setNo($no)
    {
        if (is_null($no)) {
            throw new \InvalidArgumentException('non-nullable no cannot be null');
        }
        $this->container['no'] = $no;

        return $this;
    }

    /**
     * Gets nz
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsNZ|null
     */
    public function getNz()
    {
        return $this->container['nz'];
    }

    /**
     * Sets nz
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsNZ|null $nz nz
     *
     * @return self
     */
    public function setNz($nz)
    {
        if (is_null($nz)) {
            throw new \InvalidArgumentException('non-nullable nz cannot be null');
        }
        $this->container['nz'] = $nz;

        return $this;
    }

    /**
     * Gets om
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsOM|null
     */
    public function getOm()
    {
        return $this->container['om'];
    }

    /**
     * Sets om
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsOM|null $om om
     *
     * @return self
     */
    public function setOm($om)
    {
        if (is_null($om)) {
            throw new \InvalidArgumentException('non-nullable om cannot be null');
        }
        $this->container['om'] = $om;

        return $this;
    }

    /**
     * Gets pa
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsPA|null
     */
    public function getPa()
    {
        return $this->container['pa'];
    }

    /**
     * Sets pa
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsPA|null $pa pa
     *
     * @return self
     */
    public function setPa($pa)
    {
        if (is_null($pa)) {
            throw new \InvalidArgumentException('non-nullable pa cannot be null');
        }
        $this->container['pa'] = $pa;

        return $this;
    }

    /**
     * Gets pe
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsPE|null
     */
    public function getPe()
    {
        return $this->container['pe'];
    }

    /**
     * Sets pe
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsPE|null $pe pe
     *
     * @return self
     */
    public function setPe($pe)
    {
        if (is_null($pe)) {
            throw new \InvalidArgumentException('non-nullable pe cannot be null');
        }
        $this->container['pe'] = $pe;

        return $this;
    }

    /**
     * Gets ph
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsPH|null
     */
    public function getPh()
    {
        return $this->container['ph'];
    }

    /**
     * Sets ph
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsPH|null $ph ph
     *
     * @return self
     */
    public function setPh($ph)
    {
        if (is_null($ph)) {
            throw new \InvalidArgumentException('non-nullable ph cannot be null');
        }
        $this->container['ph'] = $ph;

        return $this;
    }

    /**
     * Gets pk
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsPK|null
     */
    public function getPk()
    {
        return $this->container['pk'];
    }

    /**
     * Sets pk
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsPK|null $pk pk
     *
     * @return self
     */
    public function setPk($pk)
    {
        if (is_null($pk)) {
            throw new \InvalidArgumentException('non-nullable pk cannot be null');
        }
        $this->container['pk'] = $pk;

        return $this;
    }

    /**
     * Gets pl
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsPL|null
     */
    public function getPl()
    {
        return $this->container['pl'];
    }

    /**
     * Sets pl
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsPL|null $pl pl
     *
     * @return self
     */
    public function setPl($pl)
    {
        if (is_null($pl)) {
            throw new \InvalidArgumentException('non-nullable pl cannot be null');
        }
        $this->container['pl'] = $pl;

        return $this;
    }

    /**
     * Gets ps
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsPS|null
     */
    public function getPs()
    {
        return $this->container['ps'];
    }

    /**
     * Sets ps
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsPS|null $ps ps
     *
     * @return self
     */
    public function setPs($ps)
    {
        if (is_null($ps)) {
            throw new \InvalidArgumentException('non-nullable ps cannot be null');
        }
        $this->container['ps'] = $ps;

        return $this;
    }

    /**
     * Gets pt
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsPT|null
     */
    public function getPt()
    {
        return $this->container['pt'];
    }

    /**
     * Sets pt
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsPT|null $pt pt
     *
     * @return self
     */
    public function setPt($pt)
    {
        if (is_null($pt)) {
            throw new \InvalidArgumentException('non-nullable pt cannot be null');
        }
        $this->container['pt'] = $pt;

        return $this;
    }

    /**
     * Gets py
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsPY|null
     */
    public function getPy()
    {
        return $this->container['py'];
    }

    /**
     * Sets py
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsPY|null $py py
     *
     * @return self
     */
    public function setPy($py)
    {
        if (is_null($py)) {
            throw new \InvalidArgumentException('non-nullable py cannot be null');
        }
        $this->container['py'] = $py;

        return $this;
    }

    /**
     * Gets qa
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsQA|null
     */
    public function getQa()
    {
        return $this->container['qa'];
    }

    /**
     * Sets qa
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsQA|null $qa qa
     *
     * @return self
     */
    public function setQa($qa)
    {
        if (is_null($qa)) {
            throw new \InvalidArgumentException('non-nullable qa cannot be null');
        }
        $this->container['qa'] = $qa;

        return $this;
    }

    /**
     * Gets ro
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsRO|null
     */
    public function getRo()
    {
        return $this->container['ro'];
    }

    /**
     * Sets ro
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsRO|null $ro ro
     *
     * @return self
     */
    public function setRo($ro)
    {
        if (is_null($ro)) {
            throw new \InvalidArgumentException('non-nullable ro cannot be null');
        }
        $this->container['ro'] = $ro;

        return $this;
    }

    /**
     * Gets rs
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsRS|null
     */
    public function getRs()
    {
        return $this->container['rs'];
    }

    /**
     * Sets rs
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsRS|null $rs rs
     *
     * @return self
     */
    public function setRs($rs)
    {
        if (is_null($rs)) {
            throw new \InvalidArgumentException('non-nullable rs cannot be null');
        }
        $this->container['rs'] = $rs;

        return $this;
    }

    /**
     * Gets ru
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsRU|null
     */
    public function getRu()
    {
        return $this->container['ru'];
    }

    /**
     * Sets ru
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsRU|null $ru ru
     *
     * @return self
     */
    public function setRu($ru)
    {
        if (is_null($ru)) {
            throw new \InvalidArgumentException('non-nullable ru cannot be null');
        }
        $this->container['ru'] = $ru;

        return $this;
    }

    /**
     * Gets sa
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsSA|null
     */
    public function getSa()
    {
        return $this->container['sa'];
    }

    /**
     * Sets sa
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsSA|null $sa sa
     *
     * @return self
     */
    public function setSa($sa)
    {
        if (is_null($sa)) {
            throw new \InvalidArgumentException('non-nullable sa cannot be null');
        }
        $this->container['sa'] = $sa;

        return $this;
    }

    /**
     * Gets se
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsSE|null
     */
    public function getSe()
    {
        return $this->container['se'];
    }

    /**
     * Sets se
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsSE|null $se se
     *
     * @return self
     */
    public function setSe($se)
    {
        if (is_null($se)) {
            throw new \InvalidArgumentException('non-nullable se cannot be null');
        }
        $this->container['se'] = $se;

        return $this;
    }

    /**
     * Gets sg
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsSG|null
     */
    public function getSg()
    {
        return $this->container['sg'];
    }

    /**
     * Sets sg
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsSG|null $sg sg
     *
     * @return self
     */
    public function setSg($sg)
    {
        if (is_null($sg)) {
            throw new \InvalidArgumentException('non-nullable sg cannot be null');
        }
        $this->container['sg'] = $sg;

        return $this;
    }

    /**
     * Gets si
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsSI|null
     */
    public function getSi()
    {
        return $this->container['si'];
    }

    /**
     * Sets si
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsSI|null $si si
     *
     * @return self
     */
    public function setSi($si)
    {
        if (is_null($si)) {
            throw new \InvalidArgumentException('non-nullable si cannot be null');
        }
        $this->container['si'] = $si;

        return $this;
    }

    /**
     * Gets sk
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsSK|null
     */
    public function getSk()
    {
        return $this->container['sk'];
    }

    /**
     * Sets sk
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsSK|null $sk sk
     *
     * @return self
     */
    public function setSk($sk)
    {
        if (is_null($sk)) {
            throw new \InvalidArgumentException('non-nullable sk cannot be null');
        }
        $this->container['sk'] = $sk;

        return $this;
    }

    /**
     * Gets sm
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsSM|null
     */
    public function getSm()
    {
        return $this->container['sm'];
    }

    /**
     * Sets sm
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsSM|null $sm sm
     *
     * @return self
     */
    public function setSm($sm)
    {
        if (is_null($sm)) {
            throw new \InvalidArgumentException('non-nullable sm cannot be null');
        }
        $this->container['sm'] = $sm;

        return $this;
    }

    /**
     * Gets sv
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsSV|null
     */
    public function getSv()
    {
        return $this->container['sv'];
    }

    /**
     * Sets sv
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsSV|null $sv sv
     *
     * @return self
     */
    public function setSv($sv)
    {
        if (is_null($sv)) {
            throw new \InvalidArgumentException('non-nullable sv cannot be null');
        }
        $this->container['sv'] = $sv;

        return $this;
    }

    /**
     * Gets th
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsTH|null
     */
    public function getTh()
    {
        return $this->container['th'];
    }

    /**
     * Sets th
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsTH|null $th th
     *
     * @return self
     */
    public function setTh($th)
    {
        if (is_null($th)) {
            throw new \InvalidArgumentException('non-nullable th cannot be null');
        }
        $this->container['th'] = $th;

        return $this;
    }

    /**
     * Gets tr
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsTR|null
     */
    public function getTr()
    {
        return $this->container['tr'];
    }

    /**
     * Sets tr
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsTR|null $tr tr
     *
     * @return self
     */
    public function setTr($tr)
    {
        if (is_null($tr)) {
            throw new \InvalidArgumentException('non-nullable tr cannot be null');
        }
        $this->container['tr'] = $tr;

        return $this;
    }

    /**
     * Gets tt
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsTT|null
     */
    public function getTt()
    {
        return $this->container['tt'];
    }

    /**
     * Sets tt
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsTT|null $tt tt
     *
     * @return self
     */
    public function setTt($tt)
    {
        if (is_null($tt)) {
            throw new \InvalidArgumentException('non-nullable tt cannot be null');
        }
        $this->container['tt'] = $tt;

        return $this;
    }

    /**
     * Gets tw
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsTW|null
     */
    public function getTw()
    {
        return $this->container['tw'];
    }

    /**
     * Sets tw
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsTW|null $tw tw
     *
     * @return self
     */
    public function setTw($tw)
    {
        if (is_null($tw)) {
            throw new \InvalidArgumentException('non-nullable tw cannot be null');
        }
        $this->container['tw'] = $tw;

        return $this;
    }

    /**
     * Gets ug
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsUG|null
     */
    public function getUg()
    {
        return $this->container['ug'];
    }

    /**
     * Sets ug
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsUG|null $ug ug
     *
     * @return self
     */
    public function setUg($ug)
    {
        if (is_null($ug)) {
            throw new \InvalidArgumentException('non-nullable ug cannot be null');
        }
        $this->container['ug'] = $ug;

        return $this;
    }

    /**
     * Gets us
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsUS|null
     */
    public function getUs()
    {
        return $this->container['us'];
    }

    /**
     * Sets us
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsUS|null $us us
     *
     * @return self
     */
    public function setUs($us)
    {
        if (is_null($us)) {
            throw new \InvalidArgumentException('non-nullable us cannot be null');
        }
        $this->container['us'] = $us;

        return $this;
    }

    /**
     * Gets uy
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsUY|null
     */
    public function getUy()
    {
        return $this->container['uy'];
    }

    /**
     * Sets uy
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsUY|null $uy uy
     *
     * @return self
     */
    public function setUy($uy)
    {
        if (is_null($uy)) {
            throw new \InvalidArgumentException('non-nullable uy cannot be null');
        }
        $this->container['uy'] = $uy;

        return $this;
    }

    /**
     * Gets ve
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsVE|null
     */
    public function getVe()
    {
        return $this->container['ve'];
    }

    /**
     * Sets ve
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsVE|null $ve ve
     *
     * @return self
     */
    public function setVe($ve)
    {
        if (is_null($ve)) {
            throw new \InvalidArgumentException('non-nullable ve cannot be null');
        }
        $this->container['ve'] = $ve;

        return $this;
    }

    /**
     * Gets ye
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsYE|null
     */
    public function getYe()
    {
        return $this->container['ye'];
    }

    /**
     * Sets ye
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsYE|null $ye ye
     *
     * @return self
     */
    public function setYe($ye)
    {
        if (is_null($ye)) {
            throw new \InvalidArgumentException('non-nullable ye cannot be null');
        }
        $this->container['ye'] = $ye;

        return $this;
    }

    /**
     * Gets za
     *
     * @return \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsZA|null
     */
    public function getZa()
    {
        return $this->container['za'];
    }

    /**
     * Sets za
     *
     * @param \App\TmdbApi\Model\MovieWatchProviders200ResponseResultsZA|null $za za
     *
     * @return self
     */
    public function setZa($za)
    {
        if (is_null($za)) {
            throw new \InvalidArgumentException('non-nullable za cannot be null');
        }
        $this->container['za'] = $za;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


