<?php
/*
This file is part of Glotzenheft.

Glotzenheft is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Glotzenheft is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/**
 * SearchApi
 * PHP version 8.1
 *
 * @category Class
 * @package  App\TmdbApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * tmdb-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.26.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace App\TmdbApi\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use App\TmdbApi\ApiException;
use App\TmdbApi\Configuration;
use App\TmdbApi\FormDataProcessor;
use App\TmdbApi\HeaderSelector;
use App\TmdbApi\ObjectSerializer;

/**
 * SearchApi Class Doc Comment
 *
 * @category Class
 * @package  App\TmdbApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SearchApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'searchCollection' => [
            'application/json',
        ],
        'searchCompany' => [
            'application/json',
        ],
        'searchKeyword' => [
            'application/json',
        ],
        'searchMovie' => [
            'application/json',
        ],
        'searchMulti' => [
            'application/json',
        ],
        'searchPerson' => [
            'application/json',
        ],
        'searchTv' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation searchCollection
     *
     * Collection
     *
     * @param  string $query query (required)
     * @param  bool|null $include_adult include_adult (optional, default to false)
     * @param  string|null $language language (optional, default to 'en-US')
     * @param  int|null $page page (optional, default to 1)
     * @param  string|null $region region (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchCollection'] to see the possible values for this operation
     *
     * @throws \App\TmdbApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \App\TmdbApi\Model\SearchCollection200Response
     */
    public function searchCollection($query, $include_adult = false, $language = 'en-US', $page = 1, $region = null, string $contentType = self::contentTypes['searchCollection'][0])
    {
        list($response) = $this->searchCollectionWithHttpInfo($query, $include_adult, $language, $page, $region, $contentType);
        return $response;
    }

    /**
     * Operation searchCollectionWithHttpInfo
     *
     * Collection
     *
     * @param  string $query (required)
     * @param  bool|null $include_adult (optional, default to false)
     * @param  string|null $language (optional, default to 'en-US')
     * @param  int|null $page (optional, default to 1)
     * @param  string|null $region (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchCollection'] to see the possible values for this operation
     *
     * @throws \App\TmdbApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \App\TmdbApi\Model\SearchCollection200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function searchCollectionWithHttpInfo($query, $include_adult = false, $language = 'en-US', $page = 1, $region = null, string $contentType = self::contentTypes['searchCollection'][0])
    {
        $request = $this->searchCollectionRequest($query, $include_adult, $language, $page, $region, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\App\TmdbApi\Model\SearchCollection200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\App\TmdbApi\Model\SearchCollection200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\App\TmdbApi\Model\SearchCollection200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation searchCollectionAsync
     *
     * Collection
     *
     * @param  string $query (required)
     * @param  bool|null $include_adult (optional, default to false)
     * @param  string|null $language (optional, default to 'en-US')
     * @param  int|null $page (optional, default to 1)
     * @param  string|null $region (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchCollection'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchCollectionAsync($query, $include_adult = false, $language = 'en-US', $page = 1, $region = null, string $contentType = self::contentTypes['searchCollection'][0])
    {
        return $this->searchCollectionAsyncWithHttpInfo($query, $include_adult, $language, $page, $region, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchCollectionAsyncWithHttpInfo
     *
     * Collection
     *
     * @param  string $query (required)
     * @param  bool|null $include_adult (optional, default to false)
     * @param  string|null $language (optional, default to 'en-US')
     * @param  int|null $page (optional, default to 1)
     * @param  string|null $region (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchCollection'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchCollectionAsyncWithHttpInfo($query, $include_adult = false, $language = 'en-US', $page = 1, $region = null, string $contentType = self::contentTypes['searchCollection'][0])
    {
        $returnType = '\App\TmdbApi\Model\SearchCollection200Response';
        $request = $this->searchCollectionRequest($query, $include_adult, $language, $page, $region, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'searchCollection'
     *
     * @param  string $query (required)
     * @param  bool|null $include_adult (optional, default to false)
     * @param  string|null $language (optional, default to 'en-US')
     * @param  int|null $page (optional, default to 1)
     * @param  string|null $region (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchCollection'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function searchCollectionRequest($query, $include_adult = false, $language = 'en-US', $page = 1, $region = null, string $contentType = self::contentTypes['searchCollection'][0])
    {

        // verify the required parameter 'query' is set
        if ($query === null || (is_array($query) && count($query) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $query when calling searchCollection'
            );
        }






        $resourcePath = '/3/search/collection';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $query,
            'query', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $include_adult,
            'include_adult', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $language,
            'language', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $region,
            'region', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation searchCompany
     *
     * Company
     *
     * @param  string $query query (required)
     * @param  int|null $page page (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchCompany'] to see the possible values for this operation
     *
     * @throws \App\TmdbApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \App\TmdbApi\Model\SearchCompany200Response
     */
    public function searchCompany($query, $page = 1, string $contentType = self::contentTypes['searchCompany'][0])
    {
        list($response) = $this->searchCompanyWithHttpInfo($query, $page, $contentType);
        return $response;
    }

    /**
     * Operation searchCompanyWithHttpInfo
     *
     * Company
     *
     * @param  string $query (required)
     * @param  int|null $page (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchCompany'] to see the possible values for this operation
     *
     * @throws \App\TmdbApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \App\TmdbApi\Model\SearchCompany200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function searchCompanyWithHttpInfo($query, $page = 1, string $contentType = self::contentTypes['searchCompany'][0])
    {
        $request = $this->searchCompanyRequest($query, $page, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\App\TmdbApi\Model\SearchCompany200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\App\TmdbApi\Model\SearchCompany200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\App\TmdbApi\Model\SearchCompany200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation searchCompanyAsync
     *
     * Company
     *
     * @param  string $query (required)
     * @param  int|null $page (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchCompany'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchCompanyAsync($query, $page = 1, string $contentType = self::contentTypes['searchCompany'][0])
    {
        return $this->searchCompanyAsyncWithHttpInfo($query, $page, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchCompanyAsyncWithHttpInfo
     *
     * Company
     *
     * @param  string $query (required)
     * @param  int|null $page (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchCompany'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchCompanyAsyncWithHttpInfo($query, $page = 1, string $contentType = self::contentTypes['searchCompany'][0])
    {
        $returnType = '\App\TmdbApi\Model\SearchCompany200Response';
        $request = $this->searchCompanyRequest($query, $page, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'searchCompany'
     *
     * @param  string $query (required)
     * @param  int|null $page (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchCompany'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function searchCompanyRequest($query, $page = 1, string $contentType = self::contentTypes['searchCompany'][0])
    {

        // verify the required parameter 'query' is set
        if ($query === null || (is_array($query) && count($query) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $query when calling searchCompany'
            );
        }



        $resourcePath = '/3/search/company';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $query,
            'query', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation searchKeyword
     *
     * Keyword
     *
     * @param  string $query query (required)
     * @param  int|null $page page (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchKeyword'] to see the possible values for this operation
     *
     * @throws \App\TmdbApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \App\TmdbApi\Model\SearchKeyword200Response
     */
    public function searchKeyword($query, $page = 1, string $contentType = self::contentTypes['searchKeyword'][0])
    {
        list($response) = $this->searchKeywordWithHttpInfo($query, $page, $contentType);
        return $response;
    }

    /**
     * Operation searchKeywordWithHttpInfo
     *
     * Keyword
     *
     * @param  string $query (required)
     * @param  int|null $page (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchKeyword'] to see the possible values for this operation
     *
     * @throws \App\TmdbApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \App\TmdbApi\Model\SearchKeyword200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function searchKeywordWithHttpInfo($query, $page = 1, string $contentType = self::contentTypes['searchKeyword'][0])
    {
        $request = $this->searchKeywordRequest($query, $page, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\App\TmdbApi\Model\SearchKeyword200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\App\TmdbApi\Model\SearchKeyword200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\App\TmdbApi\Model\SearchKeyword200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation searchKeywordAsync
     *
     * Keyword
     *
     * @param  string $query (required)
     * @param  int|null $page (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchKeyword'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchKeywordAsync($query, $page = 1, string $contentType = self::contentTypes['searchKeyword'][0])
    {
        return $this->searchKeywordAsyncWithHttpInfo($query, $page, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchKeywordAsyncWithHttpInfo
     *
     * Keyword
     *
     * @param  string $query (required)
     * @param  int|null $page (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchKeyword'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchKeywordAsyncWithHttpInfo($query, $page = 1, string $contentType = self::contentTypes['searchKeyword'][0])
    {
        $returnType = '\App\TmdbApi\Model\SearchKeyword200Response';
        $request = $this->searchKeywordRequest($query, $page, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'searchKeyword'
     *
     * @param  string $query (required)
     * @param  int|null $page (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchKeyword'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function searchKeywordRequest($query, $page = 1, string $contentType = self::contentTypes['searchKeyword'][0])
    {

        // verify the required parameter 'query' is set
        if ($query === null || (is_array($query) && count($query) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $query when calling searchKeyword'
            );
        }



        $resourcePath = '/3/search/keyword';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $query,
            'query', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation searchMovie
     *
     * Movie
     *
     * @param  string $query query (required)
     * @param  bool|null $include_adult include_adult (optional, default to false)
     * @param  string|null $language language (optional, default to 'en-US')
     * @param  string|null $primary_release_year primary_release_year (optional)
     * @param  int|null $page page (optional, default to 1)
     * @param  string|null $region region (optional)
     * @param  string|null $year year (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchMovie'] to see the possible values for this operation
     *
     * @throws \App\TmdbApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \App\TmdbApi\Model\SearchMovie200Response
     */
    public function searchMovie($query, $include_adult = false, $language = 'en-US', $primary_release_year = null, $page = 1, $region = null, $year = null, string $contentType = self::contentTypes['searchMovie'][0])
    {
        list($response) = $this->searchMovieWithHttpInfo($query, $include_adult, $language, $primary_release_year, $page, $region, $year, $contentType);
        return $response;
    }

    /**
     * Operation searchMovieWithHttpInfo
     *
     * Movie
     *
     * @param  string $query (required)
     * @param  bool|null $include_adult (optional, default to false)
     * @param  string|null $language (optional, default to 'en-US')
     * @param  string|null $primary_release_year (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  string|null $region (optional)
     * @param  string|null $year (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchMovie'] to see the possible values for this operation
     *
     * @throws \App\TmdbApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \App\TmdbApi\Model\SearchMovie200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function searchMovieWithHttpInfo($query, $include_adult = false, $language = 'en-US', $primary_release_year = null, $page = 1, $region = null, $year = null, string $contentType = self::contentTypes['searchMovie'][0])
    {
        $request = $this->searchMovieRequest($query, $include_adult, $language, $primary_release_year, $page, $region, $year, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\App\TmdbApi\Model\SearchMovie200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\App\TmdbApi\Model\SearchMovie200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\App\TmdbApi\Model\SearchMovie200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation searchMovieAsync
     *
     * Movie
     *
     * @param  string $query (required)
     * @param  bool|null $include_adult (optional, default to false)
     * @param  string|null $language (optional, default to 'en-US')
     * @param  string|null $primary_release_year (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  string|null $region (optional)
     * @param  string|null $year (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchMovie'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchMovieAsync($query, $include_adult = false, $language = 'en-US', $primary_release_year = null, $page = 1, $region = null, $year = null, string $contentType = self::contentTypes['searchMovie'][0])
    {
        return $this->searchMovieAsyncWithHttpInfo($query, $include_adult, $language, $primary_release_year, $page, $region, $year, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchMovieAsyncWithHttpInfo
     *
     * Movie
     *
     * @param  string $query (required)
     * @param  bool|null $include_adult (optional, default to false)
     * @param  string|null $language (optional, default to 'en-US')
     * @param  string|null $primary_release_year (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  string|null $region (optional)
     * @param  string|null $year (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchMovie'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchMovieAsyncWithHttpInfo($query, $include_adult = false, $language = 'en-US', $primary_release_year = null, $page = 1, $region = null, $year = null, string $contentType = self::contentTypes['searchMovie'][0])
    {
        $returnType = '\App\TmdbApi\Model\SearchMovie200Response';
        $request = $this->searchMovieRequest($query, $include_adult, $language, $primary_release_year, $page, $region, $year, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'searchMovie'
     *
     * @param  string $query (required)
     * @param  bool|null $include_adult (optional, default to false)
     * @param  string|null $language (optional, default to 'en-US')
     * @param  string|null $primary_release_year (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  string|null $region (optional)
     * @param  string|null $year (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchMovie'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function searchMovieRequest($query, $include_adult = false, $language = 'en-US', $primary_release_year = null, $page = 1, $region = null, $year = null, string $contentType = self::contentTypes['searchMovie'][0])
    {

        // verify the required parameter 'query' is set
        if ($query === null || (is_array($query) && count($query) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $query when calling searchMovie'
            );
        }








        $resourcePath = '/3/search/movie';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $query,
            'query', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $include_adult,
            'include_adult', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $language,
            'language', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $primary_release_year,
            'primary_release_year', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $region,
            'region', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $year,
            'year', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation searchMulti
     *
     * Multi
     *
     * @param  string $query query (required)
     * @param  bool|null $include_adult include_adult (optional, default to false)
     * @param  string|null $language language (optional, default to 'en-US')
     * @param  int|null $page page (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchMulti'] to see the possible values for this operation
     *
     * @throws \App\TmdbApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \App\TmdbApi\Model\SearchMulti200Response
     */
    public function searchMulti($query, $include_adult = false, $language = 'en-US', $page = 1, string $contentType = self::contentTypes['searchMulti'][0])
    {
        list($response) = $this->searchMultiWithHttpInfo($query, $include_adult, $language, $page, $contentType);
        return $response;
    }

    /**
     * Operation searchMultiWithHttpInfo
     *
     * Multi
     *
     * @param  string $query (required)
     * @param  bool|null $include_adult (optional, default to false)
     * @param  string|null $language (optional, default to 'en-US')
     * @param  int|null $page (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchMulti'] to see the possible values for this operation
     *
     * @throws \App\TmdbApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \App\TmdbApi\Model\SearchMulti200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function searchMultiWithHttpInfo($query, $include_adult = false, $language = 'en-US', $page = 1, string $contentType = self::contentTypes['searchMulti'][0])
    {
        $request = $this->searchMultiRequest($query, $include_adult, $language, $page, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\App\TmdbApi\Model\SearchMulti200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\App\TmdbApi\Model\SearchMulti200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\App\TmdbApi\Model\SearchMulti200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation searchMultiAsync
     *
     * Multi
     *
     * @param  string $query (required)
     * @param  bool|null $include_adult (optional, default to false)
     * @param  string|null $language (optional, default to 'en-US')
     * @param  int|null $page (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchMulti'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchMultiAsync($query, $include_adult = false, $language = 'en-US', $page = 1, string $contentType = self::contentTypes['searchMulti'][0])
    {
        return $this->searchMultiAsyncWithHttpInfo($query, $include_adult, $language, $page, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchMultiAsyncWithHttpInfo
     *
     * Multi
     *
     * @param  string $query (required)
     * @param  bool|null $include_adult (optional, default to false)
     * @param  string|null $language (optional, default to 'en-US')
     * @param  int|null $page (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchMulti'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchMultiAsyncWithHttpInfo($query, $include_adult = false, $language = 'en-US', $page = 1, string $contentType = self::contentTypes['searchMulti'][0])
    {
        $returnType = '\App\TmdbApi\Model\SearchMulti200Response';
        $request = $this->searchMultiRequest($query, $include_adult, $language, $page, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'searchMulti'
     *
     * @param  string $query (required)
     * @param  bool|null $include_adult (optional, default to false)
     * @param  string|null $language (optional, default to 'en-US')
     * @param  int|null $page (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchMulti'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function searchMultiRequest($query, $include_adult = false, $language = 'en-US', $page = 1, string $contentType = self::contentTypes['searchMulti'][0])
    {

        // verify the required parameter 'query' is set
        if ($query === null || (is_array($query) && count($query) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $query when calling searchMulti'
            );
        }





        $resourcePath = '/3/search/multi';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $query,
            'query', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $include_adult,
            'include_adult', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $language,
            'language', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation searchPerson
     *
     * Person
     *
     * @param  string $query query (required)
     * @param  bool|null $include_adult include_adult (optional, default to false)
     * @param  string|null $language language (optional, default to 'en-US')
     * @param  int|null $page page (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchPerson'] to see the possible values for this operation
     *
     * @throws \App\TmdbApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \App\TmdbApi\Model\SearchPerson200Response
     */
    public function searchPerson($query, $include_adult = false, $language = 'en-US', $page = 1, string $contentType = self::contentTypes['searchPerson'][0])
    {
        list($response) = $this->searchPersonWithHttpInfo($query, $include_adult, $language, $page, $contentType);
        return $response;
    }

    /**
     * Operation searchPersonWithHttpInfo
     *
     * Person
     *
     * @param  string $query (required)
     * @param  bool|null $include_adult (optional, default to false)
     * @param  string|null $language (optional, default to 'en-US')
     * @param  int|null $page (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchPerson'] to see the possible values for this operation
     *
     * @throws \App\TmdbApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \App\TmdbApi\Model\SearchPerson200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function searchPersonWithHttpInfo($query, $include_adult = false, $language = 'en-US', $page = 1, string $contentType = self::contentTypes['searchPerson'][0])
    {
        $request = $this->searchPersonRequest($query, $include_adult, $language, $page, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\App\TmdbApi\Model\SearchPerson200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\App\TmdbApi\Model\SearchPerson200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\App\TmdbApi\Model\SearchPerson200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation searchPersonAsync
     *
     * Person
     *
     * @param  string $query (required)
     * @param  bool|null $include_adult (optional, default to false)
     * @param  string|null $language (optional, default to 'en-US')
     * @param  int|null $page (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchPerson'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchPersonAsync($query, $include_adult = false, $language = 'en-US', $page = 1, string $contentType = self::contentTypes['searchPerson'][0])
    {
        return $this->searchPersonAsyncWithHttpInfo($query, $include_adult, $language, $page, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchPersonAsyncWithHttpInfo
     *
     * Person
     *
     * @param  string $query (required)
     * @param  bool|null $include_adult (optional, default to false)
     * @param  string|null $language (optional, default to 'en-US')
     * @param  int|null $page (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchPerson'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchPersonAsyncWithHttpInfo($query, $include_adult = false, $language = 'en-US', $page = 1, string $contentType = self::contentTypes['searchPerson'][0])
    {
        $returnType = '\App\TmdbApi\Model\SearchPerson200Response';
        $request = $this->searchPersonRequest($query, $include_adult, $language, $page, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'searchPerson'
     *
     * @param  string $query (required)
     * @param  bool|null $include_adult (optional, default to false)
     * @param  string|null $language (optional, default to 'en-US')
     * @param  int|null $page (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchPerson'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function searchPersonRequest($query, $include_adult = false, $language = 'en-US', $page = 1, string $contentType = self::contentTypes['searchPerson'][0])
    {

        // verify the required parameter 'query' is set
        if ($query === null || (is_array($query) && count($query) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $query when calling searchPerson'
            );
        }





        $resourcePath = '/3/search/person';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $query,
            'query', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $include_adult,
            'include_adult', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $language,
            'language', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation searchTv
     *
     * TV
     *
     * @param  string $query query (required)
     * @param  int|null $first_air_date_year Search only the first air date. Valid values are: 1000..9999 (optional)
     * @param  bool|null $include_adult include_adult (optional, default to false)
     * @param  string|null $language language (optional, default to 'en-US')
     * @param  int|null $page page (optional, default to 1)
     * @param  int|null $year Search the first air date and all episode air dates. Valid values are: 1000..9999 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchTv'] to see the possible values for this operation
     *
     * @throws \App\TmdbApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \App\TmdbApi\Model\SearchTv200Response
     */
    public function searchTv($query, $first_air_date_year = null, $include_adult = false, $language = 'en-US', $page = 1, $year = null, string $contentType = self::contentTypes['searchTv'][0])
    {
        list($response) = $this->searchTvWithHttpInfo($query, $first_air_date_year, $include_adult, $language, $page, $year, $contentType);
        return $response;
    }

    /**
     * Operation searchTvWithHttpInfo
     *
     * TV
     *
     * @param  string $query (required)
     * @param  int|null $first_air_date_year Search only the first air date. Valid values are: 1000..9999 (optional)
     * @param  bool|null $include_adult (optional, default to false)
     * @param  string|null $language (optional, default to 'en-US')
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $year Search the first air date and all episode air dates. Valid values are: 1000..9999 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchTv'] to see the possible values for this operation
     *
     * @throws \App\TmdbApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \App\TmdbApi\Model\SearchTv200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function searchTvWithHttpInfo($query, $first_air_date_year = null, $include_adult = false, $language = 'en-US', $page = 1, $year = null, string $contentType = self::contentTypes['searchTv'][0])
    {
        $request = $this->searchTvRequest($query, $first_air_date_year, $include_adult, $language, $page, $year, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\App\TmdbApi\Model\SearchTv200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\App\TmdbApi\Model\SearchTv200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\App\TmdbApi\Model\SearchTv200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation searchTvAsync
     *
     * TV
     *
     * @param  string $query (required)
     * @param  int|null $first_air_date_year Search only the first air date. Valid values are: 1000..9999 (optional)
     * @param  bool|null $include_adult (optional, default to false)
     * @param  string|null $language (optional, default to 'en-US')
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $year Search the first air date and all episode air dates. Valid values are: 1000..9999 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchTv'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchTvAsync($query, $first_air_date_year = null, $include_adult = false, $language = 'en-US', $page = 1, $year = null, string $contentType = self::contentTypes['searchTv'][0])
    {
        return $this->searchTvAsyncWithHttpInfo($query, $first_air_date_year, $include_adult, $language, $page, $year, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchTvAsyncWithHttpInfo
     *
     * TV
     *
     * @param  string $query (required)
     * @param  int|null $first_air_date_year Search only the first air date. Valid values are: 1000..9999 (optional)
     * @param  bool|null $include_adult (optional, default to false)
     * @param  string|null $language (optional, default to 'en-US')
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $year Search the first air date and all episode air dates. Valid values are: 1000..9999 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchTv'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchTvAsyncWithHttpInfo($query, $first_air_date_year = null, $include_adult = false, $language = 'en-US', $page = 1, $year = null, string $contentType = self::contentTypes['searchTv'][0])
    {
        $returnType = '\App\TmdbApi\Model\SearchTv200Response';
        $request = $this->searchTvRequest($query, $first_air_date_year, $include_adult, $language, $page, $year, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'searchTv'
     *
     * @param  string $query (required)
     * @param  int|null $first_air_date_year Search only the first air date. Valid values are: 1000..9999 (optional)
     * @param  bool|null $include_adult (optional, default to false)
     * @param  string|null $language (optional, default to 'en-US')
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $year Search the first air date and all episode air dates. Valid values are: 1000..9999 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchTv'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function searchTvRequest($query, $first_air_date_year = null, $include_adult = false, $language = 'en-US', $page = 1, $year = null, string $contentType = self::contentTypes['searchTv'][0])
    {

        // verify the required parameter 'query' is set
        if ($query === null || (is_array($query) && count($query) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $query when calling searchTv'
            );
        }







        $resourcePath = '/3/search/tv';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $query,
            'query', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $first_air_date_year,
            'first_air_date_year', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $include_adult,
            'include_adult', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $language,
            'language', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $year,
            'year', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
