<?php
/*
This file is part of Glotzenheft.

Glotzenheft is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Glotzenheft is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/**
 * TrendingApi
 * PHP version 8.1
 *
 * @category Class
 * @package  App\TmdbApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TMDB API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace App\TmdbApi\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use App\TmdbApi\ApiException;
use App\TmdbApi\Configuration;
use App\TmdbApi\FormDataProcessor;
use App\TmdbApi\HeaderSelector;
use App\TmdbApi\ObjectSerializer;

/**
 * TrendingApi Class Doc Comment
 *
 * @category Class
 * @package  App\TmdbApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TrendingApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'trendingAll' => [
            'application/json',
        ],
        'trendingMovies' => [
            'application/json',
        ],
        'trendingTv' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation trendingAll
     *
     * All
     *
     * @param  string $time_window time_window (required)
     * @param  string|null $language &#x60;ISO-639-1&#x60;-&#x60;ISO-3166-1&#x60; code (optional, default to 'en-US')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['trendingAll'] to see the possible values for this operation
     *
     * @throws \App\TmdbApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \App\TmdbApi\Model\TrendingAll200Response
     */
    public function trendingAll($time_window, $language = 'en-US', string $contentType = self::contentTypes['trendingAll'][0])
    {
        list($response) = $this->trendingAllWithHttpInfo($time_window, $language, $contentType);
        return $response;
    }

    /**
     * Operation trendingAllWithHttpInfo
     *
     * All
     *
     * @param  string $time_window (required)
     * @param  string|null $language &#x60;ISO-639-1&#x60;-&#x60;ISO-3166-1&#x60; code (optional, default to 'en-US')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['trendingAll'] to see the possible values for this operation
     *
     * @throws \App\TmdbApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \App\TmdbApi\Model\TrendingAll200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function trendingAllWithHttpInfo($time_window, $language = 'en-US', string $contentType = self::contentTypes['trendingAll'][0])
    {
        $request = $this->trendingAllRequest($time_window, $language, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\App\TmdbApi\Model\TrendingAll200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\App\TmdbApi\Model\TrendingAll200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\App\TmdbApi\Model\TrendingAll200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation trendingAllAsync
     *
     * All
     *
     * @param  string $time_window (required)
     * @param  string|null $language &#x60;ISO-639-1&#x60;-&#x60;ISO-3166-1&#x60; code (optional, default to 'en-US')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['trendingAll'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function trendingAllAsync($time_window, $language = 'en-US', string $contentType = self::contentTypes['trendingAll'][0])
    {
        return $this->trendingAllAsyncWithHttpInfo($time_window, $language, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation trendingAllAsyncWithHttpInfo
     *
     * All
     *
     * @param  string $time_window (required)
     * @param  string|null $language &#x60;ISO-639-1&#x60;-&#x60;ISO-3166-1&#x60; code (optional, default to 'en-US')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['trendingAll'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function trendingAllAsyncWithHttpInfo($time_window, $language = 'en-US', string $contentType = self::contentTypes['trendingAll'][0])
    {
        $returnType = '\App\TmdbApi\Model\TrendingAll200Response';
        $request = $this->trendingAllRequest($time_window, $language, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'trendingAll'
     *
     * @param  string $time_window (required)
     * @param  string|null $language &#x60;ISO-639-1&#x60;-&#x60;ISO-3166-1&#x60; code (optional, default to 'en-US')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['trendingAll'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function trendingAllRequest($time_window, $language = 'en-US', string $contentType = self::contentTypes['trendingAll'][0])
    {

        // verify the required parameter 'time_window' is set
        if ($time_window === null || (is_array($time_window) && count($time_window) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $time_window when calling trendingAll'
            );
        }



        $resourcePath = '/3/trending/all/{time_window}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $language,
            'language', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($time_window !== null) {
            $resourcePath = str_replace(
                '{' . 'time_window' . '}',
                ObjectSerializer::toPathValue($time_window),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation trendingMovies
     *
     * Movies
     *
     * @param  string $time_window time_window (required)
     * @param  string|null $language &#x60;ISO-639-1&#x60;-&#x60;ISO-3166-1&#x60; code (optional, default to 'en-US')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['trendingMovies'] to see the possible values for this operation
     *
     * @throws \App\TmdbApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \App\TmdbApi\Model\TrendingAll200Response
     */
    public function trendingMovies($time_window, $language = 'en-US', string $contentType = self::contentTypes['trendingMovies'][0])
    {
        list($response) = $this->trendingMoviesWithHttpInfo($time_window, $language, $contentType);
        return $response;
    }

    /**
     * Operation trendingMoviesWithHttpInfo
     *
     * Movies
     *
     * @param  string $time_window (required)
     * @param  string|null $language &#x60;ISO-639-1&#x60;-&#x60;ISO-3166-1&#x60; code (optional, default to 'en-US')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['trendingMovies'] to see the possible values for this operation
     *
     * @throws \App\TmdbApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \App\TmdbApi\Model\TrendingAll200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function trendingMoviesWithHttpInfo($time_window, $language = 'en-US', string $contentType = self::contentTypes['trendingMovies'][0])
    {
        $request = $this->trendingMoviesRequest($time_window, $language, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\App\TmdbApi\Model\TrendingAll200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\App\TmdbApi\Model\TrendingAll200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\App\TmdbApi\Model\TrendingAll200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation trendingMoviesAsync
     *
     * Movies
     *
     * @param  string $time_window (required)
     * @param  string|null $language &#x60;ISO-639-1&#x60;-&#x60;ISO-3166-1&#x60; code (optional, default to 'en-US')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['trendingMovies'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function trendingMoviesAsync($time_window, $language = 'en-US', string $contentType = self::contentTypes['trendingMovies'][0])
    {
        return $this->trendingMoviesAsyncWithHttpInfo($time_window, $language, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation trendingMoviesAsyncWithHttpInfo
     *
     * Movies
     *
     * @param  string $time_window (required)
     * @param  string|null $language &#x60;ISO-639-1&#x60;-&#x60;ISO-3166-1&#x60; code (optional, default to 'en-US')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['trendingMovies'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function trendingMoviesAsyncWithHttpInfo($time_window, $language = 'en-US', string $contentType = self::contentTypes['trendingMovies'][0])
    {
        $returnType = '\App\TmdbApi\Model\TrendingAll200Response';
        $request = $this->trendingMoviesRequest($time_window, $language, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'trendingMovies'
     *
     * @param  string $time_window (required)
     * @param  string|null $language &#x60;ISO-639-1&#x60;-&#x60;ISO-3166-1&#x60; code (optional, default to 'en-US')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['trendingMovies'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function trendingMoviesRequest($time_window, $language = 'en-US', string $contentType = self::contentTypes['trendingMovies'][0])
    {

        // verify the required parameter 'time_window' is set
        if ($time_window === null || (is_array($time_window) && count($time_window) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $time_window when calling trendingMovies'
            );
        }



        $resourcePath = '/3/trending/movie/{time_window}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $language,
            'language', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($time_window !== null) {
            $resourcePath = str_replace(
                '{' . 'time_window' . '}',
                ObjectSerializer::toPathValue($time_window),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation trendingTv
     *
     * TV
     *
     * @param  string $time_window time_window (required)
     * @param  string|null $language &#x60;ISO-639-1&#x60;-&#x60;ISO-3166-1&#x60; code (optional, default to 'en-US')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['trendingTv'] to see the possible values for this operation
     *
     * @throws \App\TmdbApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \App\TmdbApi\Model\TrendingTv200Response
     */
    public function trendingTv($time_window, $language = 'en-US', string $contentType = self::contentTypes['trendingTv'][0])
    {
        list($response) = $this->trendingTvWithHttpInfo($time_window, $language, $contentType);
        return $response;
    }

    /**
     * Operation trendingTvWithHttpInfo
     *
     * TV
     *
     * @param  string $time_window (required)
     * @param  string|null $language &#x60;ISO-639-1&#x60;-&#x60;ISO-3166-1&#x60; code (optional, default to 'en-US')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['trendingTv'] to see the possible values for this operation
     *
     * @throws \App\TmdbApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \App\TmdbApi\Model\TrendingTv200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function trendingTvWithHttpInfo($time_window, $language = 'en-US', string $contentType = self::contentTypes['trendingTv'][0])
    {
        $request = $this->trendingTvRequest($time_window, $language, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\App\TmdbApi\Model\TrendingTv200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\App\TmdbApi\Model\TrendingTv200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\App\TmdbApi\Model\TrendingTv200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation trendingTvAsync
     *
     * TV
     *
     * @param  string $time_window (required)
     * @param  string|null $language &#x60;ISO-639-1&#x60;-&#x60;ISO-3166-1&#x60; code (optional, default to 'en-US')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['trendingTv'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function trendingTvAsync($time_window, $language = 'en-US', string $contentType = self::contentTypes['trendingTv'][0])
    {
        return $this->trendingTvAsyncWithHttpInfo($time_window, $language, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation trendingTvAsyncWithHttpInfo
     *
     * TV
     *
     * @param  string $time_window (required)
     * @param  string|null $language &#x60;ISO-639-1&#x60;-&#x60;ISO-3166-1&#x60; code (optional, default to 'en-US')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['trendingTv'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function trendingTvAsyncWithHttpInfo($time_window, $language = 'en-US', string $contentType = self::contentTypes['trendingTv'][0])
    {
        $returnType = '\App\TmdbApi\Model\TrendingTv200Response';
        $request = $this->trendingTvRequest($time_window, $language, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'trendingTv'
     *
     * @param  string $time_window (required)
     * @param  string|null $language &#x60;ISO-639-1&#x60;-&#x60;ISO-3166-1&#x60; code (optional, default to 'en-US')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['trendingTv'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function trendingTvRequest($time_window, $language = 'en-US', string $contentType = self::contentTypes['trendingTv'][0])
    {

        // verify the required parameter 'time_window' is set
        if ($time_window === null || (is_array($time_window) && count($time_window) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $time_window when calling trendingTv'
            );
        }



        $resourcePath = '/3/trending/tv/{time_window}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $language,
            'language', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($time_window !== null) {
            $resourcePath = str_replace(
                '{' . 'time_window' . '}',
                ObjectSerializer::toPathValue($time_window),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
